-- C7 polyphonic characters batch 2 (questions 51-100)
INSERT INTO question_banks (component, set_number, content, pinyin, metadata) VALUES
(7, 51, '他**便**利店买东西。', NULL, '{"type":"polyphonic","options":["biàn","pián"],"correctIndex":0,"explanation":"「便利」读 biàn lì，表示方便。"}'::jsonb),
(7, 52, '这首**乐**曲听起来让人心旷神怡。', NULL, '{"type":"polyphonic","options":["yuè","lè"],"correctIndex":0,"explanation":"「乐曲」读 yuè qǔ，指音乐作品。"}'::jsonb),
(7, 53, '他做事总是**磨**磨蹭蹭，半天也完不成一件。', NULL, '{"type":"polyphonic","options":["mó","mò"],"correctIndex":0,"explanation":"「磨磨蹭蹭」读 mó，表示拖延磨蹭。"}'::jsonb),
(7, 54, '这家小**磨**坊磨出来的豆腐特别香。', NULL, '{"type":"polyphonic","options":["mó","mò"],"correctIndex":1,"explanation":"「磨坊」读 mò fáng，指磨面粉的作坊。"}'::jsonb),
(7, 55, '他性格倔**强**，从不轻易向人低头。', NULL, '{"type":"polyphonic","options":["qiáng","qiǎng","jiàng"],"correctIndex":2,"explanation":"「倔强」读 jué jiàng，表示固执不屈。"}'::jsonb),
(7, 56, '这个国家**强**大起来了，人民的生活越来越好。', NULL, '{"type":"polyphonic","options":["qiáng","qiǎng","jiàng"],"correctIndex":0,"explanation":"「强大」读 qiáng dà，表示力量大。"}'::jsonb),
(7, 57, '他**强**忍着泪水，不让它流下来。', NULL, '{"type":"polyphonic","options":["qiáng","qiǎng","jiàng"],"correctIndex":1,"explanation":"「强忍」读 qiǎng rěn，表示勉强忍住。"}'::jsonb),
(7, 58, '你别在这**叨**叨了，我耳朵都快起茧子了。', NULL, '{"type":"polyphonic","options":["dāo","tāo"],"correctIndex":0,"explanation":"「叨叨」读 dāo dāo，表示唠叨。"}'::jsonb),
(7, 59, '同学们都在操场上**奔**跑锻炼。', NULL, '{"type":"polyphonic","options":["bēn","bèn"],"correctIndex":0,"explanation":"「奔跑」读 bēn pǎo，表示快跑。"}'::jsonb),
(7, 60, '他都六十岁了，还为了儿女的事到处**奔**波。', NULL, '{"type":"polyphonic","options":["bēn","bèn"],"correctIndex":0,"explanation":"「奔波」读 bēn bō，表示忙碌奔走。"}'::jsonb),
(7, 61, '你这**奔**六十的人了，身体还这么硬朗。', NULL, '{"type":"polyphonic","options":["bēn","bèn"],"correctIndex":1,"explanation":"「奔六十」读 bèn，口语中表示接近某个年龄。"}'::jsonb),
(7, 62, '你**奔**着目标一直走，别回头。', NULL, '{"type":"polyphonic","options":["bēn","bèn"],"correctIndex":1,"explanation":"「奔着」读 bèn zhe，表示朝着某个方向或目标。"}'::jsonb),
(7, 63, '他说话结结巴**巴**的，半天说不清楚。', NULL, '{"type":"polyphonic","options":["bā","ba"],"correctIndex":0,"explanation":"「结巴」读 jiē ba，但「巴」在叠词中读一声 bā。"}'::jsonb),
(7, 64, '他的**咽**喉发炎了，连喝水都疼。', NULL, '{"type":"polyphonic","options":["yān","yàn","yè"],"correctIndex":0,"explanation":"「咽喉」读 yān hóu，指喉咙部位。"}'::jsonb),
(7, 65, '他狼吞虎**咽**地吃完了饭。', NULL, '{"type":"polyphonic","options":["yān","yàn","yè"],"correctIndex":1,"explanation":"「狼吞虎咽」读 yàn，表示吞咽的动作。"}'::jsonb),
(7, 66, '他**咽**咽地哭起来，听着让人心酸。', NULL, '{"type":"polyphonic","options":["yān","yàn","yè"],"correctIndex":2,"explanation":"「呜咽」读 yè，表示低声哭泣。"}'::jsonb),
(7, 67, '他把**卷**子交上去就出来了。', NULL, '{"type":"polyphonic","options":["juǎn","juàn"],"correctIndex":1,"explanation":"「卷子」读 juàn zi，指试卷。"}'::jsonb),
(7, 68, '他把那张画**卷**起来放进了筒里。', NULL, '{"type":"polyphonic","options":["juǎn","juàn"],"correctIndex":0,"explanation":"「卷起来」读 juǎn，表示卷绕的动作。"}'::jsonb),
(7, 69, '这孩子**撒**娇的样子特别可爱。', NULL, '{"type":"polyphonic","options":["sā","sǎ"],"correctIndex":0,"explanation":"「撒娇」读 sā jiāo，表示故意做出娇气姿态。"}'::jsonb),
(7, 70, '他不小心把水**撒**了一地。', NULL, '{"type":"polyphonic","options":["sā","sǎ"],"correctIndex":1,"explanation":"「撒了一地」读 sǎ，表示洒落。"}'::jsonb),
(7, 71, '你**撒**手，我自己能走。', NULL, '{"type":"polyphonic","options":["sā","sǎ"],"correctIndex":0,"explanation":"「撒手」读 sā shǒu，表示放开手。"}'::jsonb),
(7, 72, '他费了好大劲才把绳子**解**开。', NULL, '{"type":"polyphonic","options":["jiě","jiè","xiè"],"correctIndex":0,"explanation":"「解开」读 jiě kāi，表示打开、解除。"}'::jsonb),
(7, 73, '他押**解**犯人去了外地。', NULL, '{"type":"polyphonic","options":["jiě","jiè","xiè"],"correctIndex":1,"explanation":"「押解」读 yā jiè，表示押送。"}'::jsonb),
(7, 74, '他姓**解**，这个姓不多见。', NULL, '{"type":"polyphonic","options":["jiě","jiè","xiè"],"correctIndex":2,"explanation":"作姓氏时读 xiè。"}'::jsonb),
(7, 75, '我**和**你一起去图书馆。', NULL, '{"type":"polyphonic","options":["hé","hè","huó","huò"],"correctIndex":0,"explanation":"「和」作连词读 hé。"}'::jsonb),
(7, 76, '他随声附**和**，其实根本没听懂。', NULL, '{"type":"polyphonic","options":["hé","hè","huó","huò"],"correctIndex":1,"explanation":"「附和」读 fù hè，表示跟着别人说。"}'::jsonb),
(7, 77, '妈妈在**和**面，准备包饺子。', NULL, '{"type":"polyphonic","options":["hé","hè","huó","huò"],"correctIndex":2,"explanation":"「和面」读 huó miàn，表示揉面。"}'::jsonb),
(7, 78, '把这药粉**和**匀了再喝。', NULL, '{"type":"polyphonic","options":["hé","hè","huó","huò"],"correctIndex":3,"explanation":"「和匀」读 huò yún，表示搅拌均匀。"}'::jsonb),
(7, 79, '树叶纷纷飘**落**下来。', NULL, '{"type":"polyphonic","options":["luò","lào","là"],"correctIndex":0,"explanation":"「飘落」读 luò，表示落下。"}'::jsonb),
(7, 80, '被子**落**在车上了，得回去拿。', NULL, '{"type":"polyphonic","options":["luò","lào","là"],"correctIndex":0,"explanation":"「落在」读 luò，表示遗留在某处。"}'::jsonb),
(7, 81, '奶奶做的**落**花生特别香。', NULL, '{"type":"polyphonic","options":["luò","lào","là"],"correctIndex":1,"explanation":"「落花生」读 lào huā shēng，是花生的别名。"}'::jsonb),
(7, 82, '他**落**了一个字没写。', NULL, '{"type":"polyphonic","options":["luò","lào","là"],"correctIndex":2,"explanation":"「落了」读 là，表示遗漏。"}'::jsonb),
(7, 83, '这两个数相**差**很大。', NULL, '{"type":"polyphonic","options":["chā","chà","chāi","cī"],"correctIndex":0,"explanation":"「相差」读 chā，表示差别。"}'::jsonb),
(7, 84, '他今天表现太**差**了。', NULL, '{"type":"polyphonic","options":["chā","chà","chāi","cī"],"correctIndex":1,"explanation":"「差」表示不好，读 chà。"}'::jsonb),
(7, 85, '领导派他出**差**去了。', NULL, '{"type":"polyphonic","options":["chā","chà","chāi","cī"],"correctIndex":2,"explanation":"「出差」读 chū chāi，表示因公外出。"}'::jsonb),
(7, 86, '这两件衣服颜色参**差**不齐。', NULL, '{"type":"polyphonic","options":["chā","chà","chāi","cī"],"correctIndex":3,"explanation":"「参差」读 cēn cī，表示不整齐。"}'::jsonb),
(7, 87, '这本书**给**你吧。', NULL, '{"type":"polyphonic","options":["gěi","jǐ"],"correctIndex":0,"explanation":"「给你」读 gěi nǐ，表示递给。"}'::jsonb),
(7, 88, '家里的**给**养快用完了。', NULL, '{"type":"polyphonic","options":["gěi","jǐ"],"correctIndex":1,"explanation":"「给养」读 jǐ yǎng，表示供给的物资。"}'::jsonb),
(7, 89, '他住在**宿**舍里。', NULL, '{"type":"polyphonic","options":["sù","xiǔ","xiù"],"correctIndex":0,"explanation":"「宿舍」读 sù shè，指住所。"}'::jsonb),
(7, 90, '他在朋友家住了一**宿**。', NULL, '{"type":"polyphonic","options":["sù","xiǔ","xiù"],"correctIndex":1,"explanation":"「一宿」读 yī xiǔ，表示一夜。"}'::jsonb),
(7, 91, '二十八星**宿**是古代天文概念。', NULL, '{"type":"polyphonic","options":["sù","xiǔ","xiù"],"correctIndex":2,"explanation":"「星宿」读 xīng xiù，天文术语。"}'::jsonb),
(7, 92, '这本书**载**有很多历史故事。', NULL, '{"type":"polyphonic","options":["zǎi","zài"],"correctIndex":0,"explanation":"「载有」读 zǎi，表示记载、刊登。"}'::jsonb),
(7, 93, '车上**载**满了货物。', NULL, '{"type":"polyphonic","options":["zǎi","zài"],"correctIndex":1,"explanation":"「载满」读 zài mǎn，表示装载。"}'::jsonb),
(7, 94, '这把椅子是**钉**死的，搬不动。', NULL, '{"type":"polyphonic","options":["dīng","dìng"],"correctIndex":1,"explanation":"「钉死」读 dìng sǐ，动词，表示用钉子固定。"}'::jsonb),
(7, 95, '他在墙上**钉**了一颗钉子。', NULL, '{"type":"polyphonic","options":["dīng","dìng"],"correctIndex":1,"explanation":"「钉了」读 dìng le，动词，表示钉入的动作。"}'::jsonb),
(7, 96, '他买了一盒**钉**子回来。', NULL, '{"type":"polyphonic","options":["dīng","dìng"],"correctIndex":0,"explanation":"「钉子」读 dīng zi，名词，指物件。"}'::jsonb),
(7, 97, '那家店铺已经**打**烊了。', NULL, '{"type":"polyphonic","options":["dǎ","dá"],"correctIndex":0,"explanation":"「打烊」读 dǎ yàng，表示关门歇业。"}'::jsonb),
(7, 98, '他买了两**打**铅笔。', NULL, '{"type":"polyphonic","options":["dǎ","dá"],"correctIndex":1,"explanation":"「打」作量词读 dá，一打等于十二个。"}'::jsonb),
(7, 99, '他的**兴**趣很广泛。', NULL, '{"type":"polyphonic","options":["xīng","xìng"],"correctIndex":1,"explanation":"「兴趣」读 xìng qù，表示爱好。"}'::jsonb),
(7, 100, '国家**兴**亡，匹夫有责。', NULL, '{"type":"polyphonic","options":["xīng","xìng"],"correctIndex":0,"explanation":"「兴亡」读 xīng wáng，表示兴盛与衰亡。"}'::jsonb);
