// Auto-generated from doc/monosyllabic_pinyin.md and doc/multisyllabic_pinyin.md
// Pinyin uses tone-number notation (e.g. "zhe2", "guo2 wang2", "r5" for erhua)

/** Monosyllabic character → pinyin map (1015 entries) */
export const MONO_PINYIN: Record<string, string> = {
  "哲": "zhe2",
  "洽": "qia4",
  "许": "xu3",
  "滕": "teng2",
  "缓": "huan3",
  "昂": "ang2",
  "翻": "fan1",
  "容": "rong2",
  "选": "xuan3",
  "闻": "wen2",
  "悅": "yue4",
  "围": "wei2",
  "波": "bo1",
  "信": "xin4",
  "铭": "ming2",
  "欧": "ou1",
  "测": "ce4",
  "敷": "fu1",
  "润": "run4",
  "巢": "chao2",
  "字": "zi4",
  "披": "pi1",
  "翁": "weng1",
  "辆": "liang4",
  "申": "shen1",
  "按": "an4",
  "捐": "juan1",
  "旗": "qi2",
  "黑": "hei1",
  "咬": "yao3",
  "瞥": "pie1",
  "贺": "he4",
  "失": "shi1",
  "广": "guang3",
  "晒": "shai4",
  "兵": "bing1",
  "卦": "gua4",
  "拔": "ba2",
  "君": "jun1",
  "仍": "reng2",
  "胸": "xiong1",
  "撞": "zhuang4",
  "非": "fei1",
  "眸": "mou2",
  "葬": "zang4",
  "昭": "zhao1",
  "览": "lan3",
  "脱": "tuo1",
  "嫩": "nen4",
  "所": "suo3",
  "德": "de2",
  "柳": "liu3",
  "砚": "yan4",
  "甩": "shuai3",
  "豹": "bao4",
  "壤": "rang3",
  "凑": "cou4",
  "坑": "keng1",
  "绞": "jiao3",
  "崔": "cui1",
  "我": "wo3",
  "初": "chu1",
  "蔽": "bi4",
  "匀": "yun2",
  "铝": "lv3",
  "枪": "qiang1",
  "柴": "chai2",
  "搭": "da1",
  "穷": "qiong2",
  "董": "dong3",
  "池": "chi2",
  "款": "kuan3",
  "杂": "za2",
  "此": "ci3",
  "艘": "sou1",
  "粉": "fen3",
  "阔": "kuo4",
  "您": "nin2",
  "镁": "mei3",
  "帘": "lian2",
  "械": "xie4",
  "搞": "gao3",
  "堤": "di1",
  "捡": "jian3",
  "魂": "hun2",
  "躺": "tang3",
  "瘸": "que2",
  "蛀": "zhu4",
  "游": "you2",
  "蠢": "chun3",
  "固": "gu4",
  "浓": "nong2",
  "钾": "jia3",
  "酸": "suan1",
  "莫": "mo4",
  "捧": "peng3",
  "队": "dui4",
  "耍": "shua3",
  "踹": "shuan4",
  "儿": "r5",
  "崩": "beng1",
  "饷": "xiang3",
  "攻": "gong1",
  "劳": "lao2",
  "匹": "pi3",
  "坎": "kan3",
  "蹲": "dun1",
  "女": "nv3",
  "恨": "hen4",
  "蹿": "cuan1",
  "窍": "qiao4",
  "飞": "fei1",
  "骗": "pian4",
  "封": "feng1",
  "攥": "zuan4",
  "竹": "zhu2",
  "苍": "cang1",
  "嚎": "hao2",
  "纱": "sha1",
  "吻": "wen3",
  "渠": "qu2",
  "狗": "gou3",
  "奎": "kui2",
  "署": "shu3",
  "垒": "lei3",
  "阎": "yan2",
  "蒋": "jiang3",
  "额": "e2",
  "淡": "dan4",
  "房": "fang2",
  "拢": "long3",
  "爵": "jue2",
  "猛": "meng3",
  "而": "er2",
  "军": "jun1",
  "滥": "lan4",
  "亡": "wang2",
  "软": "ruan3",
  "下": "xia4",
  "俗": "su2",
  "禀": "bing3",
  "氏": "shi4",
  "窘": "jiong3",
  "丢": "diu1",
  "捅": "tong3",
  "寻": "xun2",
  "贝": "bei4",
  "台": "tai2",
  "自": "zi4",
  "侵": "qin1",
  "入": "ru4",
  "凭": "ping2",
  "朵": "duo5",
  "条": "tiao2",
  "诈": "zha4",
  "淮": "huai2",
  "棕": "zong1",
  "滑": "hua2",
  "状": "zhuang4",
  "插": "cha1",
  "有": "you3",
  "龄": "ling2",
  "账": "zhang4",
  "垮": "kua3",
  "摸": "mo1",
  "囊": "nang2",
  "招": "zhao1",
  "酶": "mei2",
  "曳": "ye4",
  "恩": "en1",
  "赛": "sai4",
  "鳖": "bie1",
  "阅": "yue4",
  "吹": "chui1",
  "忍": "ren3",
  "吃": "chi1",
  "涮": "shuan4",
  "丝": "si1",
  "破": "po4",
  "轨": "gui3",
  "戏": "xi4",
  "谎": "huang3",
  "财": "cai2",
  "掐": "qia1",
  "曼": "man4",
  "歪": "wai1",
  "砌": "qi4",
  "用": "yong4",
  "裹": "guo3",
  "抻": "chen1",
  "岳": "yue4",
  "抓": "zhua1",
  "桃": "tao2",
  "水": "shui3",
  "淹": "yan1",
  "撼": "han4",
  "辽": "liao2",
  "纳": "na4",
  "品": "pin3",
  "饭": "fan4",
  "美": "mei3",
  "侧": "ce4",
  "北": "bei3",
  "揭": "jie1",
  "拐": "guai3",
  "费": "fei4",
  "暖": "nuan3",
  "外": "wai4",
  "盆": "pen2",
  "夏": "xia4",
  "秧": "yang1",
  "袍": "pao2",
  "鳃": "sai1",
  "磁": "ci2",
  "统": "tong3",
  "掠": "lve4",
  "廓": "kuo4",
  "峰": "feng1",
  "急": "ji2",
  "蜕": "tui4",
  "漆": "qi1",
  "垂": "chui2",
  "份": "fen4",
  "卤": "xi1",
  "痘": "dou4",
  "欢": "huan5",
  "垦": "ken3",
  "陇": "long3",
  "椎": "chui2",
  "爽": "shuang3",
  "蹬": "deng1",
  "贼": "zei2",
  "赣": "gan4",
  "舔": "tian3",
  "局": "ju2",
  "怎": "zen3",
  "挖": "wa1",
  "衡": "heng2",
  "死": "si3",
  "娘": "niang5",
  "兽": "shou4",
  "友": "you5",
  "凸": "tu1",
  "凝": "ning2",
  "杀": "sha1",
  "衔": "xian2",
  "光": "guang1",
  "去": "qu4",
  "孙": "sun1",
  "蹈": "dao3",
  "渴": "ke3",
  "鸥": "ou1",
  "庙": "miao4",
  "日": "ri4",
  "膜": "mo2",
  "蔡": "cai4",
  "让": "rang4",
  "逼": "bi1",
  "袖": "xiu4",
  "仓": "cang1",
  "尺": "chi3",
  "跌": "die1",
  "绸": "chou2",
  "汝": "ru3",
  "雄": "xiong2",
  "迈": "mai4",
  "颌": "he2",
  "贬": "bian3",
  "农": "nong2",
  "赠": "zeng4",
  "原": "yuan2",
  "均": "jun1",
  "平": "ping2",
  "准": "zhun3",
  "群": "qun2",
  "抄": "chao1",
  "责": "ze2",
  "寨": "zhai4",
  "秦": "qin2",
  "嘱": "zhu3",
  "二": "er4",
  "果": "guo3",
  "泛": "fan4",
  "宽": "kuan1",
  "淌": "tang3",
  "子": "zi5",
  "篇": "pian1",
  "察": "cha2",
  "囚": "qiu2",
  "胞": "bao1",
  "则": "ze2",
  "诉": "su5",
  "睁": "zheng1",
  "敛": "lian3",
  "导": "dao3",
  "厘": "li2",
  "运": "yun4",
  "拴": "shuan1",
  "裂": "lie4",
  "说": "shuo1",
  "脓": "nong2",
  "吼": "hou3",
  "姬": "ji1",
  "附": "fu4",
  "肠": "chang2",
  "脂": "zhi1",
  "辣": "la4",
  "弓": "gong1",
  "洒": "sa3",
  "盒": "he2",
  "退": "tui4",
  "穴": "xue2",
  "篾": "mie4",
  "再": "zai4",
  "元": "yuan2",
  "滨": "bin1",
  "耗": "hao4",
  "熏": "xun1",
  "爬": "pa2",
  "曰": "yue1",
  "鸟": "niao3",
  "投": "tou2",
  "景": "jing3",
  "随": "sui2",
  "奉": "feng4",
  "存": "cun2",
  "懂": "dong3",
  "笙": "sheng1",
  "诊": "zhen3",
  "箭": "jian4",
  "胀": "zhang4",
  "牙": "ya2",
  "丙": "bing3",
  "柔": "rou2",
  "艇": "ting3",
  "热": "re4",
  "黯": "an4",
  "持": "chi2",
  "惧": "ju4",
  "闯": "chuang3",
  "彭": "peng2",
  "内": "nei4",
  "乳": "ru3",
  "浙": "zhe4",
  "袜": "wa4",
  "稳": "wen3",
  "浦": "pu3",
  "舜": "shun4",
  "窃": "qie4",
  "心": "xin1",
  "曹": "cao2",
  "险": "xian3",
  "啃": "ken3",
  "蝶": "die2",
  "餐": "can1",
  "耳": "er3",
  "白": "bai2",
  "讲": "jiang3",
  "跟": "gen1",
  "词": "ci2",
  "揍": "zou4",
  "聊": "liao2",
  "评": "ping2",
  "忌": "ji4",
  "恒": "heng2",
  "派": "pai4",
  "全": "quan2",
  "次": "ci4",
  "铁": "tie3",
  "荒": "huang1",
  "躲": "duo3",
  "笨": "ben4",
  "辙": "zhe2",
  "钩": "gou1",
  "癌": "ai2",
  "砂": "sha1",
  "梨": "li2",
  "烤": "kao3",
  "糖": "tang2",
  "航": "hang2",
  "根": "gen1",
  "融": "rong2",
  "税": "shui4",
  "旅": "lv3",
  "庵": "an1",
  "妇": "fu4",
  "惨": "can3",
  "训": "xun5",
  "拿": "na2",
  "烘": "hong1",
  "灭": "mie4",
  "臻": "zhen1",
  "田": "tian2",
  "鸭": "ya1",
  "始": "shi3",
  "位": "wei4",
  "跷": "qiao1",
  "米": "mi3",
  "穿": "chuan1",
  "秒": "miao3",
  "抠": "kou1",
  "摆": "bai3",
  "四": "si4",
  "搓": "cuo1",
  "狂": "kuang2",
  "瓮": "weng4",
  "泣": "qi4",
  "语": "yu3",
  "愣": "leng4",
  "谷": "gu3",
  "贫": "pin2",
  "摊": "tan1",
  "取": "qu3",
  "撅": "jue1",
  "迟": "chi2",
  "焉": "yan1",
  "腮": "sai1",
  "冯": "feng2",
  "稻": "dao4",
  "瘟": "wen1",
  "镭": "lei2",
  "云": "yun2",
  "灸": "jiu3",
  "族": "zu2",
  "访": "fang3",
  "梁": "liang2",
  "靶": "ba4",
  "桌": "zhuo1",
  "饱": "bao3",
  "蹭": "ceng4",
  "明": "ming2",
  "快": "kuai4",
  "奖": "jiang3",
  "圃": "pu3",
  "唐": "tang2",
  "郑": "zheng4",
  "龙": "long2",
  "夸": "kua1",
  "永": "yong3",
  "尘": "chen2",
  "雪": "xue3",
  "潮": "chao2",
  "揪": "jiu1",
  "醒": "xing3",
  "粪": "fen4",
  "憋": "bie1",
  "脾": "pi2",
  "腐": "fu3",
  "离": "li2",
  "搜": "sou1",
  "灼": "zhuo2",
  "捞": "lao1",
  "缴": "jiao3",
  "胡": "hu2",
  "柺": "guai3",
  "蕨": "jue2",
  "买": "mai3",
  "鞭": "bian1",
  "瓢": "piao2",
  "砍": "kan3",
  "驻": "zhu4",
  "丹": "dan1",
  "扭": "niu3",
  "砸": "za2",
  "构": "gou4",
  "权": "quan2",
  "点": "dian3",
  "夜": "ye4",
  "矛": "mao2",
  "桶": "tong3",
  "怯": "qie4",
  "温": "wen1",
  "捕": "bu3",
  "鬃": "zong1",
  "末": "mo4",
  "丰": "feng1",
  "鹅": "e2",
  "塔": "ta3",
  "羹": "geng1",
  "伞": "san3",
  "锐": "rui4",
  "关": "guan1",
  "癞": "lai4",
  "想": "xiang3",
  "若": "ruo4",
  "澈": "che4",
  "蔫": "yan1",
  "床": "chuang2",
  "毡": "zhan1",
  "欺": "qi1",
  "浑": "hun2",
  "愿": "yuan4",
  "徐": "xu2",
  "炖": "tun2",
  "盯": "ding1",
  "岩": "yan2",
  "擦": "ca1",
  "炕": "kang4",
  "迷": "mi2",
  "鬓": "bin4",
  "挡": "dang3",
  "命": "ming4",
  "屯": "zhun1",
  "霜": "shuang1",
  "厢": "xiang1",
  "褶": "die2",
  "恰": "qia4",
  "胎": "tai1",
  "臣": "chen2",
  "粤": "yue4",
  "嘴": "zui3",
  "荡": "dang4",
  "慌": "huang1",
  "算": "suan4",
  "砷": "shen1",
  "如": "ru2",
  "捺": "na4",
  "绪": "xu4",
  "碟": "die2",
  "棱": "leng2",
  "特": "te4",
  "裁": "cai2",
  "抵": "di3",
  "防": "fang2",
  "洛": "luo4",
  "雨": "yu3",
  "圣": "sheng4",
  "偷": "tou1",
  "暮": "mu4",
  "晚": "wan3",
  "争": "zheng1",
  "筹": "chou2",
  "刮": "gua1",
  "范": "fan4",
  "夕": "xi1",
  "井": "jing3",
  "涉": "she4",
  "型": "xing2",
  "绒": "rong2",
  "氨": "an1",
  "怀": "huai2",
  "伙": "huo3",
  "坝": "ba4",
  "纠": "jiu1",
  "缺": "que1",
  "伍": "wu5",
  "襟": "jin1",
  "掉": "diao4",
  "趴": "pa1",
  "草": "cao3",
  "括": "kuo4",
  "粗": "cu1",
  "填": "tian2",
  "巧": "qiao3",
  "王": "wang2",
  "流": "liu2",
  "娶": "qu3",
  "鼻": "bi2",
  "廊": "lang2",
  "踩": "cai3",
  "唇": "chun2",
  "甲": "jia3",
  "坠": "zhui4",
  "栋": "dong4",
  "院": "yuan4",
  "趋": "qu1",
  "彼": "bi3",
  "孵": "fu1",
  "蹄": "ti2",
  "整": "zheng3",
  "锈": "xiu4",
  "漾": "yang4",
  "团": "tuan2",
  "键": "jian4",
  "书": "shu1",
  "筒": "tong3",
  "录": "lu4",
  "厥": "jue2",
  "腊": "xi1",
  "彩": "cai3",
  "吨": "dun1",
  "遣": "qian3",
  "迸": "beng4",
  "堵": "du3",
  "挥": "hui1",
  "远": "yuan3",
  "霉": "mei2",
  "册": "ce4",
  "偏": "pian1",
  "芽": "ya2",
  "代": "dai4",
  "锁": "suo3",
  "沟": "gou1",
  "尝": "chang2",
  "扰": "rao3",
  "硫": "liu2",
  "追": "zhui1",
  "棚": "peng2",
  "蛙": "wa1",
  "扣": "kou4",
  "桩": "zhuang1",
  "蛋": "dan4",
  "纺": "fang3",
  "怪": "guai4",
  "矫": "jiao3",
  "瑞": "rui4",
  "楼": "lou2",
  "安": "an1",
  "示": "shi4",
  "层": "ceng2",
  "劣": "lie4",
  "虹": "hong2",
  "超": "chao1",
  "民": "min2",
  "巴": "ba5",
  "蜜": "mi4",
  "响": "xiang3",
  "锭": "ding4",
  "筐": "kuang1",
  "委": "wei3",
  "害": "hai4",
  "勺": "shao2",
  "掌": "zhang3",
  "极": "ji2",
  "葛": "ge2",
  "捏": "nie1",
  "澳": "yu4",
  "戳": "chuo1",
  "耸": "song3",
  "邹": "zou1",
  "郭": "guo1",
  "酚": "fen1",
  "酉": "you3",
  "爹": "die1",
  "维": "wei2",
  "液": "ye4",
  "萍": "ping2",
  "凳": "deng4",
  "坤": "kun1",
  "面": "mian4",
  "梯": "ti1",
  "羽": "yu3",
  "耿": "geng3",
  "募": "mu4",
  "陈": "chen2",
  "批": "pi1",
  "黄": "huang2",
  "赶": "gan3",
  "文": "wen2",
  "江": "jiang1",
  "亮": "liang4",
  "尊": "zun1",
  "拼": "pin1",
  "方": "fang1",
  "赤": "chi4",
  "法": "fa3",
  "沾": "zhan1",
  "走": "zou3",
  "琴": "qin2",
  "儒": "ru2",
  "葱": "cong1",
  "夺": "duo2",
  "藻": "zao3",
  "商": "shang1",
  "槽": "cao2",
  "束": "shu4",
  "丑": "chou3",
  "弱": "ruo4",
  "临": "lin2",
  "股": "gu3",
  "赏": "shang3",
  "杭": "kang4",
  "太": "tai4",
  "虾": "xia1",
  "哨": "shao4",
  "膛": "tang2",
  "朽": "xiu3",
  "耐": "nai4",
  "宅": "zhai2",
  "拥": "yong1",
  "能": "neng2",
  "枕": "zhen3",
  "材": "cai2",
  "蛮": "man2",
  "制": "zhi4",
  "傻": "sha3",
  "并": "bing4",
  "赔": "pei2",
  "咧": "lie5",
  "津": "jin1",
  "驴": "lv2",
  "拙": "zhuo1",
  "倾": "qing1",
  "瓦": "wa3",
  "俄": "e2",
  "涩": "se4",
  "逊": "xun4",
  "添": "tian1",
  "衍": "yan3",
  "醉": "zui4",
  "推": "tui1",
  "陪": "pei2",
  "宰": "zai3",
  "鹿": "lu4",
  "牛": "niu2",
  "戒": "jie4",
  "棒": "bang4",
  "抖": "dou3",
  "雏": "chu2",
  "糟": "zao1",
  "捻": "nian3",
  "效": "xiao4",
  "皖": "huan4",
  "畔": "pan4",
  "肿": "zhong3",
  "天": "tian1",
  "者": "zhe3",
  "诚": "cheng2",
  "坪": "ping2",
  "僻": "pi4",
  "拟": "ni3",
  "貂": "diao1",
  "源": "yuan2",
  "剑": "jian4",
  "活": "huo2",
  "犬": "quan3",
  "梭": "xun4",
  "氦": "hai4",
  "苯": "ben3",
  "墩": "dun1",
  "唱": "chang4",
  "略": "lve4",
  "逃": "tao2",
  "组": "zu3",
  "滤": "lv4",
  "驱": "qu1",
  "礁": "jiao1",
  "世": "shi4",
  "铃": "ling2",
  "征": "zheng1",
  "坟": "fen2",
  "闭": "bi4",
  "腔": "qiang1",
  "抬": "tai2",
  "免": "mian3",
  "很": "hen3",
  "川": "chuan1",
  "簇": "cu4",
  "损": "sun3",
  "寡": "gua3",
  "享": "xiang3",
  "茬": "chi2",
  "松": "song1",
  "蟹": "xie4",
  "登": "deng1",
  "块": "kuai4",
  "柑": "gan1",
  "伐": "fa2",
  "愁": "chou2",
  "鞋": "xie2",
  "盾": "dun4",
  "师": "shi1",
  "供": "gong1",
  "电": "dian4",
  "国": "guo2",
  "徽": "hui1",
  "岁": "sui4",
  "竭": "jie2",
  "翡": "fei3",
  "脊": "ji2",
  "妆": "zhuang1",
  "甜": "tian2",
  "聚": "ju4",
  "闰": "run4",
  "氯": "lv4",
  "罚": "fa2",
  "伸": "shen1",
  "习": "xi2",
  "这": "zhe4",
  "他": "ta1",
  "渺": "miao3",
  "来": "lai2",
  "拣": "jian3",
  "跃": "yue4",
  "两": "liang3",
  "圆": "yuan2",
  "梢": "shao1",
  "标": "biao1",
  "谬": "miu4",
  "豆": "dou4",
  "糊": "hu5",
  "瞻": "zhan1",
  "卖": "mai4",
  "突": "tu1",
  "嗓": "sang3",
  "吴": "wu2",
  "薪": "xin1",
  "锋": "feng1",
  "瓶": "ping2",
  "靠": "kao4",
  "谜": "mi2",
  "画": "hua4",
  "饶": "rao2",
  "峦": "luan2",
  "帕": "pa4",
  "返": "fan3",
  "杯": "bei1",
  "惩": "cheng2",
  "演": "yan3",
  "惯": "guan4",
  "手": "shou3",
  "噪": "zao4",
  "恋": "lian4",
  "亚": "ya4",
  "林": "lin2",
  "啼": "ti2",
  "驹": "ju1",
  "春": "chun1",
  "闽": "min3",
  "篆": "zhuan4",
  "肯": "ken3",
  "升": "sheng1",
  "尔": "er3",
  "涡": "wo1",
  "烧": "shao1",
  "齿": "chi3",
  "舱": "cang1",
  "概": "gai4",
  "僧": "seng1",
  "问": "wen4",
  "忙": "mang2",
  "坡": "po1",
  "铜": "tong2",
  "叼": "diao1",
  "动": "dong4",
  "柱": "zhu4",
  "罕": "han3",
  "密": "mi4",
  "吮": "shun3",
  "爱": "ai4",
  "揉": "rou2",
  "象": "xiang4",
  "球": "qiu2",
  "库": "ku4",
  "悬": "xuan2",
  "繅": "sao1",
  "慎": "shen4",
  "肘": "zhou3",
  "齐": "qi2",
  "垄": "long3",
  "缘": "yuan2",
  "屋": "wu1",
  "捉": "zhuo1",
  "舀": "yao3",
  "溪": "xi1",
  "蒸": "zheng1",
  "合": "he2",
  "绕": "rao4",
  "她": "ta1",
  "满": "man3",
  "早": "zao3",
  "火": "huo3",
  "衰": "shuai1",
  "歉": "qian4",
  "鲁": "lu3",
  "幼": "you4",
  "顿": "dun4",
  "沉": "chen2",
  "延": "yan2",
  "才": "cai2",
  "邓": "shan1",
  "瞟": "piao3",
  "傍": "bang4",
  "馆": "guan3",
  "饼": "bing3",
  "颇": "po3",
  "叩": "kou4",
  "贴": "tie1",
  "墙": "qiang2",
  "蕊": "rui3",
  "瘦": "shou4",
  "念": "nian4",
  "谋": "mou2",
  "雇": "gu4",
  "聋": "long2",
  "偶": "ou3",
  "穗": "sui4",
  "抿": "min3",
  "吠": "fei4",
  "礼": "li3",
  "橙": "cheng2",
  "祝": "zhu4",
  "栏": "lan2",
  "眨": "zha3",
  "足": "zu2",
  "宝": "bao3",
  "渔": "yu2",
  "辉": "hui1",
  "万": "wan4",
  "柯": "ke1",
  "汤": "tang1",
  "窄": "zhai3",
  "踱": "duo2",
  "呆": "dai1",
  "垫": "dian4",
  "蹦": "beng4",
  "含": "han2",
  "孟": "meng4",
  "歌": "ge1",
  "帆": "fan1",
  "荣": "rong2",
  "乏": "fa2",
  "饥": "ji1",
  "虚": "xu1",
  "简": "jian3",
  "踢": "ti1",
  "月": "yue4",
  "居": "ju1",
  "俏": "qiao4",
  "痛": "tong4",
  "诗": "shi1",
  "策": "ce4",
  "雾": "wu4",
  "浇": "jiao1",
  "洼": "wa1",
  "棋": "qi2",
  "索": "suo3",
  "避": "bi4",
  "雕": "diao1",
  "确": "que4",
  "铡": "zha2",
  "栖": "qi1",
  "戴": "dai4",
  "孤": "gu1",
  "撵": "nian3",
  "晴": "qing2",
  "短": "duan3",
  "丸": "wan2",
  "志": "zhi4",
  "帝": "di4",
  "蓬": "peng2",
  "岸": "an4",
  "禹": "yu3",
  "洪": "hong2",
  "促": "cu4",
  "充": "chong1",
  "棍": "gun4",
  "赖": "lai4",
  "届": "jie4",
  "跳": "tiao4",
  "赘": "zhui4",
  "请": "qing3",
  "藕": "ou3",
  "沽": "gu1",
  "河": "he2",
  "装": "zhuang1",
  "拎": "lin1",
  "镶": "xiang1",
  "镇": "zhen4",
  "留": "liu2",
  "窑": "yao2",
  "虽": "sui1",
  "冒": "mao4",
  "魏": "wei4",
  "惹": "re3",
  "牢": "lao2",
  "肝": "gan1",
  "猿": "yuan2",
  "基": "ji1",
  "窗": "chuang1",
  "飘": "piao1",
  "倦": "juan4",
  "窝": "wo1",
  "舌": "she2",
  "拖": "tuo1",
  "堪": "kan1",
  "眯": "mi1",
  "碾": "nian3",
  "阵": "zhen4",
  "胚": "pei1",
  "住": "zhu4",
  "博": "bo2",
  "袁": "yuan2",
  "髻": "ji4",
  "脸": "lian3",
  "设": "she4",
  "炎": "yan2",
  "窟": "ku1",
  "该": "gai1",
  "恐": "kong3",
  "古": "gu3",
  "伶": "ling5",
  "其": "qi2",
  "至": "zhi4",
  "疼": "teng2",
  "隔": "ge2",
  "摘": "zhai1",
  "生": "sheng1",
  "碰": "peng4",
  "裙": "qun2",
  "项": "xiang4",
  "佐": "zuo3",
  "后": "hou4",
  "蜂": "feng1",
  "疗": "liao2",
  "厂": "chang3",
  "叹": "tan4",
  "忠": "zhong1",
  "腥": "xing1",
  "迂": "yu1",
  "忘": "wang4",
  "兜": "dou1",
  "扯": "che3",
  "喂": "wei4",
  "从": "cong2",
  // C1 DEFAULT_CHARACTERS additions
  "八": "ba1",
  "把": "ba3",
  "百": "bai3",
  "办": "ban4",
  "半": "ban4",
  "包": "bao1",
  "本": "ben3",
  "比": "bi3",
  "边": "bian1",
  "表": "biao3",
  "别": "bie2",
  "不": "bu4",
  "菜": "cai4",
  "茶": "cha2",
  "长": "chang2",
  "常": "chang2",
  "场": "chang3",
  "车": "che1",
  "城": "cheng2",
  "出": "chu1",
  "船": "chuan2",
  "村": "cun1",
  "大": "da4",
  "带": "dai4",
  "到": "dao4",
  "的": "de5",
  "等": "deng3",
  "地": "di4",
  "东": "dong1",
  "都": "dou1",
  "读": "du2",
  "对": "dui4",
  "多": "duo1",
  "发": "fa1",
};

/** Multisyllabic word → pinyin map (523 entries) */
export const MULTI_PINYIN: Record<string, string> = {
  "国王": "guo2 wang2",
  "今日": "jin1 ri4",
  "虐待": "nve4 dai4",
  "花瓶儿": "hua1 ping2 r5",
  "难怪": "nan2 guai4",
  "产品": "chan3 pin3",
  "掉头": "diao4 tou2",
  "遭受": "zao1 shou4",
  "露馅儿": "lu4 xian4 r5",
  "人群": "ren2 qun2",
  "压力": "ya1 li4",
  "材料": "cai2 liao4",
  "窘迫": "jiong3 po4",
  "亏损": "kui1 sun3",
  "翱翔": "ao2 xiang2",
  "永远": "yong3 yuan3",
  "一辈子": "yi1 bei4 zi5",
  "佛典": "fu2 dian3",
  "沙尘": "sha1 chen2",
  "存在": "cun2 zai4",
  "请求": "qing3 qiu2",
  "累赘": "lei4 zhui4",
  "发愣": "fa1 leng4",
  "外面": "wai4 mian4",
  "酒盅儿": "jiu3 chong1 r5",
  "似乎": "shi4 hu5",
  "怎么": "zen3 me5",
  "赔偿": "pei2 chang2",
  "勘察": "kan1 cha2",
  "妨碍": "fang2 ai4",
  "辨别": "bian4 bie2",
  "调整": "diao4 zheng3",
  "少女": "shao3 nv3",
  "做活儿": "zuo4 huo2 r5",
  "完全": "wan2 quan2",
  "霓虹灯": "ni2 hong2 deng1",
  "疯狂": "feng1 kuang2",
  "从而": "cong2 er2",
  "入学": "ru4 xue2",
  "夸奖": "kua1 jiang3",
  "回去": "hui2 qu4",
  "篡夺": "cuan4 duo2",
  "秧歌": "yang1 ge1",
  "夏季": "xia4 ji4",
  "钢铁": "gang1 tie3",
  "通讯": "tong1 xun4",
  "敏感": "min3 gan3",
  "不速之客": "bu4 su4 zhi1 ke4",
  "奶粉": "nai3 fen3",
  "在这儿": "zai4 zhe4 r5",
  "雄伟": "xiong2 wei3",
  "婴儿": "ying1 r5",
  "群众": "qun2 zhong4",
  "电压": "dian4 ya1",
  "吵架": "chao3 jia4",
  "连续": "lian2 xu4",
  "枕头": "zhen3 tou2",
  "新娘": "xin1 niang5",
  "航空": "hang2 kong1",
  "富翁": "fu4 weng1",
  "节日": "jie2 ri4",
  "上层": "shang4 ceng2",
  "核算": "he2 suan4",
  "大学生": "da4 xue2 sheng1",
  "名词": "ming2 ci2",
  "况且": "kuang4 qie3",
  "抓阄儿": "zhua1 jiu1 r5",
  "麻烦": "ma2 fan2",
  "追求": "zhui1 qiu2",
  "佛教": "fu2 jiao4",
  "包子": "bao1 zi5",
  "原则": "yuan2 ze2",
  "热量": "re4 liang4",
  "农村": "nong2 cun1",
  "履行": "lv3 xing2",
  "骨髓": "gu3 sui3",
  "概括拐弯儿": "gai4 kuo4 guai3 wan1 r5",
  "配套": "pei4 tao4",
  "玻璃": "bo1 li2",
  "探索": "tan4 suo3",
  "创作": "chuang4 zuo4",
  "后跟儿": "hou4 gen1 r5",
  "全体": "quan2 ti3",
  "春光": "chun1 guang1",
  "运动": "yun4 dong4",
  "神经质": "shen2 jing1 zhi4",
  "昂首": "ang2 shou3",
  "衰变": "shuai1 bian4",
  "诋毁": "di3 hui3",
  "黑暗": "hei1 an4",
  "挖苦": "wa1 ku3",
  "发票": "fa1 piao4",
  "贫穷": "pin2 qiong2",
  "一目了然": "yi1 mu4 le5 ran2",
  "全身断层": "quan2 shen1 duan4 ceng2",
  "允许": "yun3 xu3",
  "障碍": "zhang4 ai4",
  "小瓮儿": "xiao3 weng4 r5",
  "坏人": "huai4 ren2",
  "愉快": "yu2 kuai4",
  "打算": "da3 suan4",
  "来临": "lai2 lin2",
  "灭亡": "mie4 wang2",
  "仍然": "reng2 ran2",
  "方法论": "fang1 fa3 lun4",
  "挫折": "cuo4 zhe2",
  "压迫": "ya1 po4",
  "至今": "zhi4 jin1",
  "减轻": "jian3 qing1",
  "罪恶": "zui4 e4",
  "脸盘儿": "lian3 pan2 r5",
  "教训": "jiao4 xun5",
  "签订": "qian1 ding4",
  "告诉": "gao4 su5",
  "黑夜唱歌儿": "hei1 ye4 chang4 ge1 r5",
  "疲倦": "pi2 juan4",
  "电话": "dian4 hua4",
  "口吻": "kou3 wen3",
  "宾馆": "bin1 guan3",
  "物价": "wu4 jia4",
  "宫女": "gong1 nv3",
  "荒谬": "huang1 miu4",
  "思想": "si1 xiang3",
  "穷苦": "qiong2 ku3",
  "挑剔": "tiao1 ti1",
  "从容": "cong2 rong2",
  "侦查": "zhen1 cha2",
  "作用": "zuo4 yong4",
  "玩耍": "wan2 shua3",
  "窗子": "chuang1 zi5",
  "给以": "gei3 yi3",
  "南半球": "nan2 ban4 qiu2",
  "重量": "zhong4 liang4",
  "蜜枣儿佛学": "mi4 zao3 r5 fu2 xue2",
  "特别": "te4 bie2",
  "命令": "ming4 ling4",
  "周而复始": "zhou1 er2 fu4 shi3",
  "战略": "zhan4 lve4",
  "昂然": "ang2 ran2",
  "分别": "fen1 bie2",
  "祖宗": "zu3 zong1",
  "凉爽": "liang2 shuang3",
  "撇开": "pie1 kai1",
  "画家": "hua4 jia1",
  "走访": "zou3 fang3",
  "因而": "yin1 er2",
  "身边": "shen1 bian1",
  "下游": "xia4 you2",
  "看法": "kan4 fa3",
  "哥们儿": "ge1 men5 r5",
  "篡改": "cuan4 gai3",
  "圈套": "quan1 tao4",
  "群体": "qun2 ti3",
  "效率": "xiao4 lv4",
  "思维": "si1 wei2",
  "英雄": "ying1 xiong2",
  "牛顿": "niu2 dun4",
  "冲刷": "chong1 shua1",
  "大伙儿": "da4 huo3 r5",
  "流传": "liu2 chuan2",
  "轻快": "qing1 kuai4",
  "多么": "duo1 me5",
  "奥秘": "ao4 mi4",
  "状况": "zhuang4 kuang4",
  "军事": "jun1 shi4",
  "太阳能": "tai4 yang2 neng2",
  "面前": "mian4 qian2",
  "谬误": "miu4 wu4",
  "灯泡儿": "deng1 pao4 r5",
  "从此": "cong2 ci3",
  "扫帚": "sao3 zhou5",
  "贯彻": "guan4 che4",
  "土匪": "tu3 fei3",
  "商标": "shang1 biao1",
  "戏曲": "xi4 qu1",
  "佛像": "fu2 xiang4",
  "主人翁": "zhu3 ren2 weng1",
  "同伴": "tong2 ban4",
  "收回": "shou1 hui2",
  "厌倦": "yan4 juan4",
  "提成儿": "ti2 cheng2 r5",
  "日益": "ri4 yi4",
  "怀念": "huai2 nian4",
  "洼地": "wa1 de5",
  "男女": "nan2 nv3",
  "喜欢": "xi3 huan5",
  "军阀": "jun1 fa2",
  "效果": "xiao4 guo3",
  "舌头": "she2 tou2",
  "傍晚": "bang4 wan3",
  "深化": "shen1 hua4",
  "线轴儿": "xian4 zhou2 r5",
  "协作": "xie2 zuo4",
  "定额": "ding4 e2",
  "随便": "sui2 bian4",
  "分配": "fen1 pei4",
  "牛仔裤": "niu2 zi3 ku4",
  "勉强": "mian3 qiang2",
  "穷人": "qiong2 ren2",
  "摧毁": "cui1 hui3",
  "大褂儿": "da4 gua4 r5",
  "率领": "lv4 ling3",
  "母亲": "mu3 qin1",
  "昂扬": "ang2 yang2",
  "栅栏": "zha4 lan2",
  "佛寺": "fu2 si4",
  "旋转": "xuan2 zhuan3",
  "原因": "yuan2 yin1",
  "价格": "jia4 ge2",
  "长颈鹿": "zhang3 jing3 lu4",
  "装备": "zhuang1 bei4",
  "句子": "ju4 zi5",
  "操纵": "cao1 zong4",
  "逗乐儿": "dou4 le4 r5",
  "手稿": "shou3 gao3",
  "观察": "guan1 cha2",
  "恰好": "qia4 hao3",
  "往返": "wang3 fan3",
  "谬论": "miu4 lun4",
  "标志": "biao1 zhi4",
  "不约而同": "bu4 yue1 er2 tong2",
  "佛经": "fu2 jing1",
  "成本": "cheng2 ben3",
  "闺女": "gui1 nv3",
  "强调": "qiang2 diao4",
  "侵略": "qin1 lve4",
  "能量": "neng2 liang4",
  "打嗝儿": "da3 ge2 r5",
  "收藏": "shou1 cang2",
  "迅速": "xun4 su4",
  "烧饼": "shao1 bing3",
  "豪华": "hao2 hua2",
  "框子": "kuang1 zi5",
  "后天": "hou4 tian1",
  "怀抱": "huai2 bao4",
  "荧光屏": "ying2 guang1 ping2",
  "家长": "jia1 zhang3",
  "何尝": "he2 chang2",
  "可以": "ke3 yi3",
  "然而": "ran2 er2",
  "胸脯": "xiong1 pu2",
  "开窍儿": "kai1 qiao4 r5",
  "盗贼": "dao4 zei2",
  "无穷": "wu2 qiong2",
  "有劲儿": "you3 jin4 r5",
  "席卷": "xi2 juan3",
  "于是": "yu2 shi4",
  "陡坡": "dou3 po1",
  "繁荣": "fan2 rong2",
  "镇压": "zhen4 ya1",
  "拉链儿": "la1 lian4 r5",
  "宣传": "xuan1 chuan2",
  "拇指": "mu5 zhi3",
  "安慰": "an1 wei4",
  "四周": "si4 zhou1",
  "矮小": "ai3 xiao3",
  "你们": "ni3 men5",
  "做梦": "zuo4 meng4",
  "非法": "fei1 fa3",
  "留声机": "liu2 sheng1 ji1",
  "候鸟": "hou5 niao3",
  "协商": "xie2 shang1",
  "首饰": "shou3 shi4",
  "柔软": "rou2 ruan3",
  "刺激": "ci4 ji1",
  "跑腿儿": "pao3 tui3 r5",
  "夸张": "kua1 zhang1",
  "而且": "er2 qie3",
  "下降": "xia4 jiang4",
  "坎肩儿": "kan3 jian1 r5",
  "全面": "quan2 mian4",
  "工作": "gong1 zuo4",
  "画外音": "hua4 wai4 yin1",
  "差别": "cha4 bie2",
  "衰老": "shuai1 lao3",
  "训练": "xun5 lian4",
  "聪明": "cong1 ming2",
  "课本": "ke4 ben3",
  "红包儿": "hong2 bao1 r5",
  "回归": "hui2 gui1",
  "所有制": "suo3 you3 zhi4",
  "强度": "qiang2 du4",
  "表皮": "biao3 pi2",
  "盖子": "gai4 zi5",
  "长城": "chang2 cheng2",
  "顶点": "ding3 dian3",
  "合同": "he2 tong2",
  "掠夺": "lve4 duo2",
  "挨个儿": "ai1 ge4 r5",
  "佛法": "fu2 fa3",
  "赞美": "zan4 mei3",
  "消费": "xiao1 fei4",
  "速率": "su4 lv4",
  "恩情": "en1 qing2",
  "问卷": "wen4 juan3",
  "人民": "ren2 min2",
  "不以为然": "bu4 yi3 wei4 ran2",
  "军队": "jun1 dui4",
  "融合": "rong2 he2",
  "根据地": "gen1 ju4 de5",
  "汹涌": "xiong1 yong3",
  "成名": "cheng2 ming2",
  "意思": "yi4 si1",
  "仍旧": "reng2 jiu4",
  "棉球儿": "mian2 qiu2 r5",
  "虽说": "sui1 shuo1",
  "病人": "bing4 ren2",
  "天下": "tian1 xia4",
  "被窝儿": "bei4 wo1 r5",
  "权利": "quan2 li4",
  "终身": "zhong1 shen1",
  "扭转": "niu3 zhuan3",
  "破坏": "po4 huai4",
  "宾主": "bin1 zhu3",
  "价值": "jia4 zhi2",
  "刷新": "shua1 xin1",
  "大娘": "da4 niang5",
  "爱好": "ai4 hao3",
  "感慨": "gan3 kai3",
  "临床": "lin2 chuang2",
  "猫头鹰": "mao1 tou2 ying1",
  "拱桥": "gong3 qiao2",
  "循环": "xun2 huan2",
  "咳嗽": "hai1 sou5",
  "舞蹈": "wu3 dao3",
  "缺乏": "que1 fa2",
  "昂贵": "ang2 gui4",
  "快板儿": "kuai4 ban3 r5",
  "频率": "pin2 lv4",
  "花鸟": "hua1 niao3",
  "内外": "nei4 wai4",
  "贩子": "fan4 zi5",
  "粗略早春": "cu1 lve4 zao3 chun1",
  "善良": "shan4 liang2",
  "不言而喻": "bu4 yan2 er2 yu4",
  "磁场": "ci2 chang3",
  "成品": "cheng2 pin3",
  "飞快": "fei1 kuai4",
  "说话": "shuo1 hua4",
  "家畜": "jia1 chu4",
  "灵敏": "ling2 min3",
  "全部": "quan2 bu4",
  "症状": "zheng4 zhuang4",
  "趋向": "qu1 xiang4",
  "探讨": "tan4 tao3",
  "作风": "zuo4 feng1",
  "儿童": "r5 tong2",
  "蚂蚁": "ma3 yi3",
  "日见": "ri4 jian4",
  "火星儿": "huo3 xing1 r5",
  "仙女": "xian5 nv3",
  "及时格外": "ji2 shi2 ge2 wai4",
  "摧残": "cui1 can2",
  "国务院": "guo2 wu5 yuan4",
  "牙刷儿": "ya2 shua1 r5",
  "棒槌": "bang4 zhui4",
  "存亡": "cun2 wang2",
  "搬运": "ban1 yun4",
  "横扫": "heng2 sao3",
  "粉碎": "fen3 sui4",
  "何况": "he2 kuang4",
  "缺点": "que1 dian3",
  "连累": "lian2 lei4",
  "墙壁": "qiang2 bi4",
  "管理": "guan3 li3",
  "丢掉": "diu1 diao4",
  "按钮": "an4 niu3",
  "操作": "cao1 zuo4",
  "遵照": "zun1 zhao4",
  "维持": "wei2 chi2",
  "金丝猴周年": "jin1 si1 hou2 zhou1 nian2",
  "抓获": "zhua1 huo4",
  "黄昏": "huang2 hun1",
  "脸盆儿": "lian3 pen2 r5",
  "榨取": "zha4 qu3",
  "眉头": "mei2 tou2",
  "千瓦": "qian1 wa3",
  "笼子": "long2 zi5",
  "权力": "quan2 li4",
  "门洞儿": "men2 dong4 r5",
  "打倒": "da3 dao4",
  "硫酸": "liu2 suan1",
  "双亲": "shuang1 qin1",
  "别扭": "bie2 niu3",
  "崩溃": "beng1 kui4",
  "妇女": "fu4 nv3",
  "一直": "yi1 zhi2",
  "必须": "bi4 xu1",
  "木偶": "mu4 ou3",
  "逃窜帮忙": "tao2 cuan4 bang1 mang2",
  "科学家": "ke1 xue2 jia1",
  "场所": "chang3 suo3",
  "另外": "ling4 wai4",
  "从小": "cong2 xiao3",
  "人影儿": "ren2 ying3 r5",
  "将军": "jiang1 jun1",
  "清楚": "qing1 chu5",
  "调和": "diao4 he2",
  "悄声": "qiao1 sheng1",
  "上下": "shang4 xia4",
  "拥有": "yong1 you3",
  "补丁": "bu3 ding1",
  "侨眷": "qiao2 juan4",
  "在乎": "zai4 hu5",
  "完备": "wan2 bei4",
  "骄傲": "jiao1 ao4",
  "质量": "zhi4 liang4",
  "杀害": "sha1 hai4",
  "吹牛妥当": "chui1 niu2 tuo3 dang1",
  "工程师": "gong1 cheng2 shi1",
  "作品": "zuo4 pin3",
  "送信儿": "song4 xin4 r5",
  "首尾": "shou3 wei3",
  "折磨": "zhe2 mo2",
  "安全": "an1 quan2",
  "个别": "ge4 bie2",
  "奔跑": "ben1 pao3",
  "如下": "ru2 xia4",
  "关卡": "guan1 ka3",
  "扯皮": "che3 pi2",
  "来不及": "lai2 bu4 ji2",
  "棉花": "mian2 hua1",
  "财产": "cai2 chan3",
  "钉子": "ding1 zi5",
  "以外": "yi3 wai4",
  "跳高儿": "tiao4 gao1 r5",
  "畅所欲言": "chang4 suo3 yu4 yan2",
  "恰当": "qia4 dang1",
  "砂轮儿": "sha1 lun2 r5",
  "丰满": "feng1 man3",
  "疟疾": "nve4 ji2",
  "表演": "biao3 yan3",
  "加工": "jia1 gong1",
  "开外": "kai1 wai4",
  "寻找": "xun2 zhao3",
  "生存力": "sheng1 cun2 li4",
  "花脸": "hua1 lian3",
  "匪徒": "fei3 tu2",
  "红润": "hong2 run4",
  "观光": "guan1 guang1",
  "弱点": "ruo4 dian3",
  "零碎": "ling2 sui4",
  "渗透": "shen4 tou4",
  "半道儿": "ban4 dao4 r5",
  "白色": "bai2 se4",
  "老爷": "lao3 ye5",
  "飘带": "piao1 dai4",
  "拼命媒人": "pin1 ming4 mei2 ren2",
  "锥子": "zhui1 zi5",
  "侵占": "qin1 zhan4",
  "显微镜": "xian3 wei1 jing4",
  "持久": "chi2 jiu3",
  "宾客": "bin1 ke4",
  "手绢儿": "shou3 juan4 r5",
  "选举": "xuan3 ju3",
  "一丝不苟": "yi1 si1 bu4 gou3",
  "垂危": "chui2 wei1",
  "封闭": "feng1 bi4",
  "王后": "wang2 hou4",
  "啄木鸟": "zhuo2 mu4 niao3",
  "高昂": "gao1 ang2",
  "舒坦": "shu1 tan3",
  "安排": "an1 pai2",
  "地层": "de5 ceng2",
  "支持": "zhi1 chi2",
  "元素": "yuan2 su4",
  "夏天": "xia4 tian1",
  "麻花儿": "ma2 hua1 r5",
  "思索": "si1 suo3",
  "南方": "nan2 fang1",
  "总额": "zong3 e2",
  "家乡": "jia1 xiang1",
  "紧缺": "jin3 que1",
  "苟且": "gou3 qie3",
  "纳粹": "na4 cui4",
  "稳当": "wen3 dang1",
  "区别": "qu1 bie2",
  "小翁儿": "xiao3 weng1 r5",
  "开业": "kai1 ye4",
  "定律": "ding4 lv4",
  "上吊": "shang4 diao4",
  "空子": "kong1 zi5",
  "剥削": "bo1 xue1",
  "哈密瓜": "ha1 mi4 gua1",
  "眷恋": "juan4 lian4",
  "分工": "fen1 gong1",
  "配合红军": "pei4 he2 hong2 jun1",
  "创造": "chuang4 zao4",
  "应用": "ying1 yong4",
  "快乐": "kuai4 le4",
  "抑扬顿挫": "yi4 yang2 dun4 cuo4",
  "规律": "gui1 lv4",
  "村子": "cun1 zi5",
  "瓦斯": "wa3 si1",
  "品位": "pin3 wei4",
  "牙签儿": "ya2 qian1 r5",
  "血管": "xue4 guan3",
  "人才": "ren2 cai2",
  "家伙": "jia1 huo3",
  "美酒": "mei3 jiu3",
  "书卷": "shu1 juan3",
  "苗头": "miao2 tou2",
  "爱国": "ai4 guo2",
  "温柔": "wen1 rou2",
  "抢险": "qiang3 xian3",
  "按照": "an4 zhao4",
  "高涨": "gao1 zhang3",
  "碎步儿": "sui4 bu4 r5",
  "操办": "cao1 ban4",
  "命运": "ming4 yun4",
  "进化论": "jin4 hua4 lun4",
  "涅槃": "nie4 pan2",
  "钢镚儿": "gang1 beng4 r5",
  "山川": "shan1 chuan1",
  "飘动": "piao1 dong4",
  "录音机": "lu4 yin1 ji1",
  "正确": "zheng4 que4",
  "总结": "zong3 jie2",
  "天鹅": "tian1 e2",
  "开垦": "kai1 ken3",
  "课程": "ke4 cheng2",
  "遵循": "zun1 xun2",
  "有的放矢": "you3 de5 fang4 shi3",
  // C6 平翘舌音 (zhcs)
  "杂志": "za2 zhi4",
  "竹子": "zhu2 zi5",
  "自习": "zi4 xi2",
  "知识": "zhi1 shi2",
  "早餐": "zao3 can1",
  "城市": "cheng2 shi4",
  "三十": "san1 shi2",
  "山水": "shan1 shui3",
  "十四": "shi2 si4",
  "事实": "shi4 shi2",
  "四十": "si4 shi2",
  "时事": "shi2 shi4",
  "种子": "zhong3 zi5",
  "中山": "zhong1 shan1",
  "出色": "chu1 se4",
  "出操": "chu1 cao1",
  "春蚕": "chun1 can2",
  "春茶": "chun1 cha2",
  "纯粹": "chun2 cui4",
  "辞职": "ci2 zhi2",
  "此时": "ci3 shi2",
  "超市": "chao1 shi4",
  "硕士": "shuo4 shi4",
  "数字": "shu4 zi4",
  "松鼠": "song1 shu3",
  "素食": "su4 shi2",
  "随时": "sui2 shi2",
  "损失": "sun3 shi1",
  "组织": "zu3 zhi1",
  "阻止": "zu3 zhi3",
  "作战": "zuo4 zhan4",
  "作者": "zuo4 zhe3",
  "差错": "cha1 cuo4",
  "插错": "cha1 cuo4",
  "伸缩": "shen1 suo1",
  "深思": "shen1 si1",
  "生死": "sheng1 si3",
  "生产": "sheng1 chan3",
  // C6 前后鼻音 (nng)
  "北京": "bei3 jing1",
  "上海": "shang4 hai3",
  "天津": "tian1 jin1",
  "重庆": "zhong4 qing4",
  "长江": "chang2 jiang1",
  "黄河": "huang2 he2",
  "黄山": "huang2 shan1",
  "心情": "xin1 qing2",
  "心静": "xin1 jing4",
  "姓名": "xing4 ming2",
  "性命": "xing4 ming4",
  "拼音": "pin1 yin1",
  "平音": "ping2 yin1",
  "英语": "ying1 yu3",
  "硬语": "ying4 yu3",
  "经常": "jing1 chang2",
  "进入": "jin4 ru4",
  "金星": "jin1 xing1",
  "精心": "jing1 xin1",
  "亲人": "qin1 ren2",
  "清人": "qing1 ren2",
  "信任": "xin4 ren4",
  "新任": "xin1 ren4",
  "认真": "ren4 zhen1",
  "任正": "ren4 zheng4",
  "人参": "ren2 shen1",
  "人生": "ren2 sheng1",
  "深沉": "shen1 chen2",
  "生成": "sheng1 cheng2",
  "分针": "fen1 zhen1",
  "风筝": "feng1 zheng1",
  "奔腾": "ben1 teng2",
  "本能": "ben3 neng2",
  "愤恨": "fen4 hen4",
  "风横": "feng1 heng2",
  "门诊": "men2 zhen3",
  "蒙眬": "meng2 long2",
  "根本": "gen1 ben3",
  "更笨": "geng4 ben4",
  // C6 边鼻音 (ln)
  "奶奶": "nai3 nai3",
  "来来": "lai2 lai2",
  "牛奶": "niu2 nai3",
  "流利": "liu2 li4",
  "那里": "na4 li3",
  "哪里": "na3 li3",
  "褴褛": "lan2 lv3",
  "蓝绿": "lan2 lv4",
  "南岭": "nan2 ling3",
  "辽宁": "liao2 ning2",
  "南宁": "nan2 ning2",
  "内陆": "nei4 lu4",
  "冷暖": "leng3 nuan3",
  "冷热": "leng3 re4",
  "老年": "lao3 nian2",
  "老娘": "lao3 niang2",
  "尼龙": "ni2 long2",
  "泥泞": "ni2 ning4",
  "篱笆": "li2 ba5",
  "泥巴": "ni2 ba5",
  "农历": "nong2 li4",
  "奴隶": "nu2 li4",
  "努力": "nu3 li4",
  "绿篱": "lv4 li2",
  "女篮": "nv3 lan2",
  "男篮": "nan2 lan2",
  "来年": "lai2 nian2",
  "老农": "lao3 nong2",
  "脑力": "nao3 li4",
  "劳力": "lao2 li4",
  "南路": "nan2 lu4",
  "拦路": "lan2 lu4",
  "烂泥": "lan4 ni2",
  "蓝鸟": "lan2 niao3",
  "岭南": "ling3 nan2",
  "林南": "lin2 nan2",
};
