// src/lib/quest/stage-questions.ts
import type { StageNumber, StageQuestions } from "./types";

export const STAGE_QUESTIONS: Record<StageNumber, StageQuestions> = {
  /* ─── Stage 1 ─── 1 recording group (20 mono) ─── */
  1: {
    recordingGroups: [
      {
        label: "Monosyllabic Characters",
        type: "monosyllabic",
        words: [
          "哲", "洽", "滕", "昂", "翻", "悦", "铭", "欧", "巢", "披",
          "缘", "屋", "捉", "舀", "溪", "蒸", "合", "绕", "她", "满",
        ],
        category: "read_syllable",
        pinyin: [
          "zhé", "qià", "téng", "áng", "fān", "yuè", "míng", "ōu", "cháo", "pī",
          "yuán", "wū", "zhuō", "yǎo", "xī", "zhēng", "hé", "rào", "tā", "mǎn",
        ],
      },
    ],
    mcqQuestions: [
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["太阳", "热头", "日头"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["下雨", "落雨", "掉点儿"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["地瓜", "红薯", "番薯"],
        correctIndex: 1,
      },
      {
        prompt: "一（ ）钥匙",
        options: ["把", "根", "条", "个", "串"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）皮带",
        options: ["条", "根", "段", "个", "副"],
        correctIndex: 0,
      },
      {
        context: "这根绳子太长了，需要剪掉一截。",
        prompt: "请选择加点字的正确读音。",
        options: ["cháng", "zhǎng"],
        correctIndex: 0,
        highlightedChar: "长",
      },
      {
        context: "几年不见，这孩子长高了不少。",
        prompt: "请选择加点字的正确读音。",
        options: ["cháng", "zhǎng"],
        correctIndex: 1,
        highlightedChar: "长",
      },
      {
        context: "你行动快一点，我们要迟到了。",
        prompt: "请选择加点字的正确读音。",
        options: ["xíng", "háng"],
        correctIndex: 0,
        highlightedChar: "行",
      },
      {
        context: "我在银行办了点业务，耽误了一会儿。",
        prompt: "请选择加点字的正确读音。",
        options: ["xíng", "háng"],
        correctIndex: 1,
        highlightedChar: "行",
      },
      {
        context: "这部电影很好看，推荐你也去瞧瞧。",
        prompt: "请选择加点字的正确读音。",
        options: ["hǎo", "hào"],
        correctIndex: 0,
        highlightedChar: "好",
      },
    ],
  },

  /* ─── Stage 2 ─── 2 recording groups (15 mono + 15 multi) ─── */
  2: {
    recordingGroups: [
      {
        label: "Monosyllabic Characters",
        type: "monosyllabic",
        words: [
          "明", "快", "奖", "圃", "唐",
          "瘟", "蕨", "驴", "渺", "猿",
          "寻", "贝", "台", "自", "侵",
        ],
        category: "read_syllable",
        pinyin: [
          "míng", "kuài", "jiǎng", "pǔ", "táng",
          "wēn", "jué", "lǘ", "miǎo", "yuán",
          "xún", "bèi", "tái", "zì", "qīn",
        ],
      },
      {
        label: "Multisyllabic Words",
        type: "multisyllabic",
        words: [
          "拐弯儿", "探索", "取经", "贫穷", "一目了然",
          "挫折", "减轻", "罪恶", "金箍棒", "紧箍咒",
          "恰好", "往返", "谬论", "标志", "不约而同",
        ],
        category: "read_word",
        pinyin: [
          "guǎi wān er", "tàn suǒ", "qǔ jīng", "pín qióng", "yí mù liǎo rán",
          "cuò zhé", "jiǎn qīng", "zuì è", "jīn gū bàng", "jǐn gū zhòu",
          "qià hǎo", "wǎng fǎn", "miù lùn", "biāo zhì", "bù yuē ér tóng",
        ],
      },
    ],
    mcqQuestions: [
      {
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["我先走", "我走先", "我走头先"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["你吃饭头先", "你吃饭先", "你先吃饭"],
        correctIndex: 2,
      },
      {
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["你听得懂不懂？", "你听不听得懂？", "你听得吗？"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["我比他三岁大", "我大他三岁", "我比他大三岁"],
        correctIndex: 2,
      },
      {
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["他有来没有？", "他来没来？", "他来没？"],
        correctIndex: 1,
      },
      {
        context: "二十八星宿是古代天文概念。",
        prompt: "请选择加点字的正确读音。",
        options: ["sù", "xiǔ", "xiù"],
        correctIndex: 2,
        highlightedChar: "宿",
      },
      {
        context: "这本书载有很多历史故事。",
        prompt: "请选择加点字的正确读音。",
        options: ["zǎi", "zài"],
        correctIndex: 0,
        highlightedChar: "载",
      },
      {
        context: "车上载满了货物。",
        prompt: "请选择加点字的正确读音。",
        options: ["zǎi", "zài"],
        correctIndex: 1,
        highlightedChar: "载",
      },
      {
        context: "这把椅子是钉死的，搬不动。",
        prompt: "请选择加点字的正确读音。",
        options: ["dīng", "dìng"],
        correctIndex: 1,
        highlightedChar: "钉",
      },
      {
        context: "他在墙上钉了一颗钉子。",
        prompt: "请选择加点字的正确读音。",
        options: ["dīng", "dìng"],
        correctIndex: 1,
        highlightedChar: "钉",
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["苍蝇", "胡蝇", "乌蝇", "蚨蝇"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["开水", "滚水", "百滚汤"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["地瓜", "红薯", "番薯"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["日里", "日中", "白天", "日时"],
        correctIndex: 2,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["土豆", "洋芋", "薯仔", "马铃薯"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）伞",
        options: ["把", "顶", "张", "个", "柄"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）棍子",
        options: ["根", "条", "支", "段", "个"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）狗",
        options: ["条", "只", "头", "个", "匹"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）花",
        options: ["朵", "枝", "束", "盆", "棵"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）毛巾",
        options: ["条", "块", "张", "个", "方"],
        correctIndex: 0,
      },
    ],
  },

  /* ─── Stage 3 ─── 3 recording groups (15 mono + 15 multi + C4 passage) ─── */
  3: {
    recordingGroups: [
      {
        label: "Monosyllabic Characters",
        type: "monosyllabic",
        words: [
          "藕", "镶", "飘", "窝", "堪",
          "眯", "碾", "髻", "窟", "魏",
          "傻", "并", "赔", "咧", "津",
        ],
        category: "read_syllable",
        pinyin: [
          "ǒu", "xiāng", "piāo", "wō", "kān",
          "mī", "niǎn", "jì", "kū", "wèi",
          "shǎ", "bìng", "péi", "liě", "jīn",
        ],
      },
      {
        label: "Multisyllabic Words",
        type: "multisyllabic",
        words: [
          "昂首", "衰变", "诋毁", "法术", "齐天大圣",
          "白骨精", "脸盘儿", "教训", "筋斗云", "天宫",
          "聪明", "课本", "红包儿", "回归", "所有制",
        ],
        category: "read_word",
        pinyin: [
          "áng shǒu", "shuāi biàn", "dǐ huǐ", "fǎ shù", "qí tiān dà shèng",
          "bái gǔ jīng", "liǎn pán er", "jiào xun", "jīn dǒu yún", "tiān gōng",
          "cōng míng", "kè běn", "hóng bāo ér", "huí guī", "suǒ yǒu zhì",
        ],
      },
      {
        label: "Passage Reading",
        type: "passage",
        words: [],
        passageText: "黄沙翻涌，铁锈味刺鼻。你刚握紧法杖，前方沙地骤然塌陷——白骨夫人出手了。\n\n五根骨刺从沙下无声刺出。你闪避着念出第一个字，声调却因喘息微微走样。她尖笑一声，骨刺在半空转向，擦着你的肋骨划过，衣襟撕开，皮肉火辣辣地疼。你踉跄后退，她枯白的手指凌空点出，骨箭从身后嗖嗖射来——你躲开三根，第四根钉住你的左肩，整个人被扯得向后一仰。\n\n不能慌。你站稳脚跟，再次开口。这一次声音稳了，字字饱满，掷地有声。那个词念完的瞬间，法杖顶端炸开一团金光——光芒扫过，她那张娇媚的人脸寸寸碎裂，露出白骨骷髅的本来面目。她尖叫着，身形凝固的刹那，你冲了上去。\n\n她挥手召来三面骨墙。你念一个字，第一面炸裂；再念一字，第二面粉碎；第三字出口，最后一面骨墙连同骨盾同时崩成齑粉。法杖抵住她的额骨，金光灼得她眼眶里的鬼火剧烈颤抖。\n\n她还想挣扎，干枯的手爪抓向你的喉咙。但你的下一个词已经出口，稳得像钉进骨头里。那个词落下时，她的身体从指尖开始溃散，化作流沙簌簌坠地，只留下一句警告在风中消散。",
        category: "read_chapter",
      },
    ],
    mcqQuestions: [
      {
        context: "悟空刚握紧法杖，前方沙地骤然塌陷——白骨夫人出手了。五根骨刺从沙下无声刺出，悟空闪避着念出第一个字，声调却因喘息微微走样。",
        prompt: "请选择加点字的正确读音。",
        options: ["xíng", "háng"],
        correctIndex: 0,
        highlightedChar: "行",
      },
      {
        context: "她尖笑一声，骨刺在半空转向，擦着悟空的肋骨划过。",
        prompt: "请选择加点字的正确读音。",
        options: ["zhuǎn", "zhuàn"],
        correctIndex: 0,
        highlightedChar: "转",
      },
      {
        context: "悟空被骨箭钉住肩膀，整个人被扯得向后一仰，险些落在地上。",
        prompt: "请选择加点字的正确读音。",
        options: ["luò", "là"],
        correctIndex: 0,
        highlightedChar: "落",
      },
      {
        context: "不能慌。悟空站稳脚跟，深吸一口气，重新开口。",
        prompt: "请选择加点字的正确读音。",
        options: ["zhòng", "chóng"],
        correctIndex: 1,
        highlightedChar: "重",
      },
      {
        context: "那个词念完的瞬间，法杖顶端炸开一团金光，照得沙漠如同白昼。",
        prompt: "请选择加点字的正确读音。",
        options: ["dé", "de"],
        correctIndex: 1,
        highlightedChar: "得",
      },
      {
        context: "光芒扫过，她那张娇媚的人脸寸寸碎裂，露出白骨骷髅的本来面目。",
        prompt: "请选择加点字的正确读音。",
        options: ["chū", "chù"],
        correctIndex: 0,
        highlightedChar: "出",
      },
      {
        context: "她尖叫着，身形凝固的刹那，悟空抡起法杖冲了上去。",
        prompt: "请选择加点字的正确读音。",
        options: ["shā", "chà"],
        correctIndex: 1,
        highlightedChar: "刹",
      },
      {
        context: "悟空念出一个字，第一面骨墙应声炸裂；再念一字，第二面为齑粉。",
        prompt: "请选择加点字的正确读音。",
        options: ["wéi", "wèi"],
        correctIndex: 0,
        highlightedChar: "为",
      },
      {
        context: "法杖抵住她的额骨，金光灼得她眼眶里的鬼火剧烈颤抖。",
        prompt: "请选择加点字的正确读音。",
        options: ["de", "dé"],
        correctIndex: 0,
        highlightedChar: "得",
      },
      {
        context: "她的身体从指尖开始溃散，化作流沙簌簌坠地，只留下一句警告在风中消散。",
        prompt: "请选择加点字的正确读音。",
        options: ["xiāo", "xuè"],
        correctIndex: 0,
        highlightedChar: "消",
      },
      {
        context: "他在便利店买东西。",
        prompt: "请选择加点字的正确读音。",
        options: ["biàn", "pián"],
        correctIndex: 0,
        highlightedChar: "便",
      },
      {
        context: "这首乐曲听起来让人心旷神怡。",
        prompt: "请选择加点字的正确读音。",
        options: ["yuè", "lè"],
        correctIndex: 0,
        highlightedChar: "乐",
      },
      {
        context: "他做事总是磨磨蹭蹭，半天也完不成一件。",
        prompt: "请选择加点字的正确读音。",
        options: ["mó", "mò"],
        correctIndex: 0,
        highlightedChar: "磨",
      },
      {
        context: "这家小磨坊磨出来的豆腐特别香。",
        prompt: "请选择加点字的正确读音。",
        options: ["mó", "mò"],
        correctIndex: 1,
        highlightedChar: "磨",
      },
      {
        context: "他性格倔强，从不轻易向人低头。",
        prompt: "请选择加点字的正确读音。",
        options: ["qiáng", "qiǎng", "jiàng"],
        correctIndex: 2,
        highlightedChar: "强",
      },
      {
        context: "王老师在教室批改作业。",
        prompt: "请选择加点字的正确读音。",
        options: ["jiào", "jiāo"],
        correctIndex: 0,
        highlightedChar: "教",
      },
      {
        context: "妈妈教我怎么做红烧肉。",
        prompt: "请选择加点字的正确读音。",
        options: ["jiào", "jiāo"],
        correctIndex: 1,
        highlightedChar: "教",
      },
      {
        context: "他为人正直，大家都愿意和他交朋友。",
        prompt: "请选择加点字的正确读音。",
        options: ["wéi", "wèi"],
        correctIndex: 0,
        highlightedChar: "为",
      },
      {
        context: "你为什么不早点告诉我？",
        prompt: "请选择加点字的正确读音。",
        options: ["wéi", "wèi"],
        correctIndex: 1,
        highlightedChar: "为",
      },
      {
        context: "我没钱买那么贵的东西。",
        prompt: "请选择加点字的正确读音。",
        options: ["méi", "mò"],
        correctIndex: 0,
        highlightedChar: "没",
      },
    ],
  },
  /* ─── Stage 4 ─── 3 recording groups (15 mono + 15 multi + tongue twister passage) ─── */
  4: {
    recordingGroups: [
      {
        label: "Monosyllabic Characters",
        type: "monosyllabic",
        words: [
          "狼", "月", "山", "爪", "眼",
          "颇", "叩", "贴", "墙", "蕊",
          "风", "影", "嚎", "林", "夜",
        ],
        category: "read_syllable",
        pinyin: [
          "láng", "yuè", "shān", "zhuǎ", "yǎn",
          "pō", "kòu", "tiē", "qiáng", "ruǐ",
          "fēng", "yǐng", "háo", "lín", "yè",
        ],
      },
      {
        label: "Multisyllabic Words",
        type: "multisyllabic",
        words: [
          "月狼魔", "月光", "狼嚎", "山径", "利爪",
          "定律", "上吊", "空子", "剥削", "哈密瓜",
          "总额", "家乡", "紧缺", "苟且", "纳粹",
        ],
        category: "read_word",
        pinyin: [
          "yuè láng mó", "yuè guāng", "láng háo", "shān jìng", "lì zhuǎ",
          "dìng lǜ", "shàng diào", "kòng zi", "bō xuē", "hā mì guā",
          "zǒng é", "jiā xiāng", "jǐn quē", "gǒu qiě", "nà cuì",
        ],
      },
      {
        label: "Tongue Twister",
        type: "passage",
        words: [],
        passageText: "四是四，十是十，十四是十四，四十是四十。别把十四说四十，也别把四十说十四。报纸是报纸，包子是包子。报纸包包子，包子包报纸？",
        category: "read_chapter",
      },
    ],
    mcqQuestions: [
      {
        context: "悟空侧身闪避狼魔的利爪，脚下踩到一块松动的石头。",
        prompt: "请选择加点字的正确读音。",
        options: ["tóu", "tou"],
        correctIndex: 1,
        highlightedChar: "头",
      },
      {
        context: "狼魔的眼睛在月光下闪着绿光，死死地盯着悟空的一举一动。",
        prompt: "请选择加点字的正确读音。",
        options: ["dīng", "dìng"],
        correctIndex: 0,
        highlightedChar: "盯",
      },
      {
        context: "悟空念错一个字，狼魔的利爪划过他的肩头，鲜血渗了出来。",
        prompt: "请选择加点字的正确读音。",
        options: ["guò", "guo"],
        correctIndex: 1,
        highlightedChar: "过",
      },
      {
        context: "几番回合后，狼魔终于支撑不住，转身逃入密林深处。",
        prompt: "请选择加点字的正确读音。",
        options: ["zhù", "zhu"],
        correctIndex: 1,
        highlightedChar: "住",
      },
      {
        context: "我着急出门，忘了带钥匙。",
        prompt: "请选择加点字的正确读音。",
        options: ["zháo", "zhe", "zhāo"],
        correctIndex: 0,
        highlightedChar: "着",
      },
      {
        context: "他笑着跟我打招呼。",
        prompt: "请选择加点字的正确读音。",
        options: ["zháo", "zhe", "zhāo"],
        correctIndex: 1,
        highlightedChar: "着",
      },
      {
        context: "你这着棋走错了，应该防守才对。",
        prompt: "请选择加点字的正确读音。",
        options: ["zháo", "zhe", "zhāo"],
        correctIndex: 2,
        highlightedChar: "着",
      },
      {
        context: "衣服晾在外面，已经干了。",
        prompt: "请选择加点字的正确读音。",
        options: ["gān", "gàn"],
        correctIndex: 0,
        highlightedChar: "干",
      },
      {
        context: "你干什么工作？",
        prompt: "请选择加点字的正确读音。",
        options: ["gān", "gàn"],
        correctIndex: 1,
        highlightedChar: "干",
      },
      {
        context: "他发现了一个秘密。",
        prompt: "请选择加点字的正确读音。",
        options: ["fā", "fà"],
        correctIndex: 0,
        highlightedChar: "发",
      },
      {
        prompt: "一（ ）钢琴",
        options: ["架", "台", "个", "座", "具"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）被子",
        options: ["床", "条", "张", "个", "套"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）眼镜",
        options: ["副", "个", "架", "只", "对"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）门",
        options: ["扇", "道", "个", "座", "孔"],
        correctIndex: 0,
      },
      {
        context: "悟空沿着山路往前走，月光洒在他身上。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["他不晓得狼魔藏在哪", "他不知道狼魔藏在哪", "他不晓的狼魔藏在哪"],
        correctIndex: 1,
      },
      {
        context: "狼魔从暗处扑过来，悟空立刻举起法杖。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这场战斗免不了要打", "这场战斗免不得要打", "这场战斗免不掉要打"],
        correctIndex: 0,
      },
      {
        context: "狼魔的眼睛在黑暗中发光。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["它的眼睛像两团鬼火", "它的眼睛好像两团鬼火", "它的眼睛好似两团鬼火"],
        correctIndex: 1,
      },
      {
        context: "悟空念错了字，狼魔趁机攻击。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["悟空的肩膀让抓伤了", "悟空的肩膀被抓伤了", "悟空的肩膀给抓伤了"],
        correctIndex: 1,
      },
      {
        context: "战斗结束后，狼魔逃进深山。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["悟空持续往前走", "悟空连续往前走", "悟空继续往前走"],
        correctIndex: 2,
      },
      {
        prompt: "一（ ）猪",
        options: ["头", "只", "条", "个", "口"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）云",
        options: ["朵", "片", "团", "块", "层"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）蜡烛",
        options: ["根", "支", "条", "个", "盏"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）火车",
        options: ["列", "辆", "节", "台", "条"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）鼓",
        options: ["面", "个", "只", "架", "通"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["这孩子可爱真", "这孩子可爱得很", "这孩子真可爱"],
        correctIndex: 2,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["他住上海", "他在上海住", "他住在上海"],
        correctIndex: 2,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["你帮我能吗？", "你能帮我吗？", "你可不可以帮我？"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["我写这封信完了", "我写了这封信完", "这封信我写完了"],
        correctIndex: 2,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["他跳很好舞", "他跳舞很好", "他跳舞跳得很好"],
        correctIndex: 2,
      },
    ],
  },
  /* ─── Stage 5 ─── 4 recording groups (10 multi + 10 multi + 10 n/l + C4 passage) ─── */
  5: {
    recordingGroups: [
      {
        label: "Multisyllabic Words I",
        type: "multisyllabic",
        words: [
          "遮天蔽日", "弥漫", "翻涌不息", "庞然大物", "凝神戒备",
          "腐化", "咆哮", "轰鸣", "簌簌落下", "赤红如血",
        ],
        category: "read_word",
        pinyin: [
          "zhē tiān bì rì", "mí màn", "fān yǒng bù xī", "páng rán dà wù", "níng shén jiè bèi",
          "fǔ huà", "páo xiào", "hōng míng", "sù sù luò xià", "chì hóng rú xuè",
        ],
      },
      {
        label: "Multisyllabic Words II",
        type: "multisyllabic",
        words: [
          "灼热气流", "迸发金光", "削弱", "尖锐", "挑起",
          "穿梭", "潮湿", "震耳欲聋", "竹叶", "簌簌",
        ],
        category: "read_word",
        pinyin: [
          "zhuó rè qì liú", "bèng fā jīn guāng", "xuē ruò", "jiān ruì", "tiǎo qǐ",
          "chuān suō", "cháo shī", "zhèn ěr yù lóng", "zhú yè", "sù sù",
        ],
      },
      {
        label: "N/L Contrast Words",
        type: "multisyllabic",
        words: [
          "南岭", "辽宁", "南宁", "内陆", "能量",
          "冷暖", "冷热", "老年", "老娘", "尼龙",
        ],
        category: "read_word",
        pinyin: [
          "nán lǐng", "liáo níng", "nán níng", "nèi lù", "néng liàng",
          "lěng nuǎn", "lěng rè", "lǎo nián", "lǎo niáng", "ní lóng",
        ],
      },
      {
        label: "Passage Reading",
        type: "passage",
        words: [],
        passageText: "雾气像活的。你踏入竹林第一步就感觉到了——那些灰白的雾缠绕着你的脚踝，顺着裤管往上爬。竹子密密麻麻，遮天蔽日，十步之外只剩模糊的影。你握紧法杖，放慢脚步，指节因为用力而泛白。\n\n地面突然抖了一下。\n\n你顿住，侧耳倾听。又是几下颤抖，竹叶簌簌落下，打着旋儿飘进雾里。颤抖越来越剧烈，变成有节奏的震动——咚、咚、咚——像巨人的心跳，像战鼓，从竹林深处逼近。你压低身形，法杖横在胸前。\n\n雾气猛地被撕开。\n\n一个巨大的黑影冲了出来，头顶双角赤红如血，四蹄踏得地面隆隆作响。牛魔王！你还没看清，那庞然大物已经到了跟前。你侧身一滚，牛角擦着你的腰际划过，撞在身后的竹子上，碗口粗的竹子拦腰折断。\n\n你翻身跃起，开口念出第一个字。声调刚出口，你就知道自己错了——喘息未定，音走了样。牛魔王猛地回头，一角挑在你的肋下。你整个人被掀上半空，重重摔在竹叶堆里，胸口闷得像压了块石头。\n\n不能慌。你撑着法杖站起来，深吸一口气，再次开口。这一次声音稳了，字字饱满，掷地有声。那个词念完的瞬间，法杖顶端炸开一团金光——光芒直直劈向牛魔王，他庞大的身躯一晃，后退半步，发出一声痛苦的咆哮。\n\n你冲了上去。你踩着自己的节奏，每一步配合一次发音。牛魔王低头冲来，你念出一个字，金光如锤砸在他的脑门上；再念一字，金光劈在他的肩胛；第三字出口，金光直直刺进他的胸口。牛魔王终于支撑不住，庞大的身躯轰然跪地，然后侧倒下去，震得满林竹叶纷飞。\n\n你收起法杖，喘着粗气。雾气渐渐散去，竹林恢复了寂静。你抹了把额头的汗，继续向前走去。",
        category: "read_chapter",
      },
    ],
    mcqQuestions: [
      {
        context: "你踏入迷雾竹林，四周的雾气越来越浓。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["雾大得啥也看不见", "雾大得什么也看不见", "雾大得嘛也看不见"],
        correctIndex: 1,
      },
      {
        context: "地面突然震动起来，竹叶簌簌落下。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这是啥子声音", "这是什么声音", "这是啥声音"],
        correctIndex: 1,
      },
      {
        context: "雾气中隐约现出一个巨大的黑影。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["俺得小心点", "我得小心点", "咱得小心点"],
        correctIndex: 1,
      },
      {
        context: "牛魔王从雾中冲了出来，鼻息喷出灼热的气流。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这牛魔真厉害", "这牛魔忒厉害", "这牛魔好厉害"],
        correctIndex: 0,
      },
      {
        context: "没有退路，只有一战。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这回八成得拼命", "这回肯定得拼命", "这回指定得拼命"],
        correctIndex: 1,
      },
      {
        context: "悟空举起法杖，准备迎战牛魔王。",
        prompt: "下面哪个句子语法正确？",
        options: ["悟空念咒语给牛魔王", "悟空念给牛魔王咒语", "悟空念咒语对牛魔王"],
        correctIndex: 0,
      },
      {
        context: "牛魔王从雾气中冲出来，气势汹汹。",
        prompt: "下面哪个句子语法正确？",
        options: ["悟空躲开了牛魔王的角", "悟空躲牛魔王的角开了", "悟空躲开角牛魔王的"],
        correctIndex: 0,
      },
      {
        context: "悟空念错了一个字，牛魔王趁机攻击。",
        prompt: "下面哪个句子语法正确？",
        options: ["牛魔王把角刺向悟空", "牛魔王把角对悟空刺", "牛魔王把悟空刺角"],
        correctIndex: 0,
      },
      {
        context: "法杖迸发出耀眼的金光，牛魔王的力量被削弱了。",
        prompt: "下面哪个句子语法正确？",
        options: ["金光让牛魔王削弱了力量", "金光削弱了牛魔王的力量", "金光把力量削弱了牛魔王"],
        correctIndex: 1,
      },
      {
        context: "经过一番苦战，牛魔王终于倒下了。",
        prompt: "下面哪个句子语法正确？",
        options: ["悟空击败了牛魔王", "悟空击败牛魔王了", "悟空把牛魔王击败了"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["馒头", "馍", "蒸饼", "馍馍"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["辣椒", "番椒", "辣子", "海椒"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["毛巾", "面巾", "手巾仔", "面帕"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["手套", "手袜", "手笠", "手笼"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["冰箱", "雪柜", "冰柜", "雪橱"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["手机", "手电", "移动", "大哥大"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["火车", "铁龙", "铁车", "火轮车"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["鸡蛋", "鸡子", "鸡春", "鸡卵"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["猪肉", "猪猡肉", "豚肉", "豕肉"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["西红柿", "番茄", "洋柿子", "红茄"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）桌子",
        options: ["张", "条", "把", "个", "台"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）钢笔",
        options: ["支", "根", "把", "个", "管"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）衣服",
        options: ["件", "条", "套", "身", "个"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）井",
        options: ["口", "眼", "个", "座", "孔"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）马",
        options: ["匹", "头", "只", "条", "个"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）窗户",
        options: ["扇", "个", "面", "道", "孔"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）糖",
        options: ["颗", "块", "粒", "个", "包"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）军舰",
        options: ["艘", "架", "只", "条", "座"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）耳朵",
        options: ["只", "个", "对", "扇", "片"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）墙",
        options: ["面", "道", "堵", "个", "扇"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）葡萄",
        options: ["颗", "粒", "个", "串", "枝"],
        correctIndex: 3,
      },
    ],
  },
  /* ─── Stage 6 ─── 5 recording groups (10 multi + 10 multi + 10 multi + 5 n/l + 5 n/l) ─── */
  6: {
    recordingGroups: [
      {
        label: "Multisyllabic Words I",
        type: "multisyllabic",
        words: [
          "豁然开朗", "涟漪", "婉转啼鸣", "暴风雨", "缝隙",
          "守护者", "天庭试炼", "熠熠生辉", "颔首", "云朵儿",
        ],
        category: "read_word",
        pinyin: [
          "huò rán kāi lǎng", "lián yī", "wǎn zhuǎn tí míng", "bào fēng yǔ", "fèng xì",
          "shǒu hù zhě", "tiān tíng shì liàn", "yì yì shēng huī", "hàn shǒu", "yún duǒ er",
        ],
      },
      {
        label: "Multisyllabic Words II",
        type: "multisyllabic",
        words: [
          "全力以赴", "半信半疑", "恍然大悟", "从容不迫", "不知所措",
          "念念有词", "目瞪口呆", "振振有词", "云彩", "花瓣儿",
        ],
        category: "read_word",
        pinyin: [
          "quán lì yǐ fù", "bàn xìn bàn yí", "huǎng rán dà wù", "cóng róng bù pò", "bù zhī suǒ cuò",
          "niàn niàn yǒu cí", "mù dèng kǒu dāi", "zhèn zhèn yǒu cí", "yún cai", "huā bàn er",
        ],
      },
      {
        label: "Multisyllabic Words III",
        type: "multisyllabic",
        words: [
          "震耳欲聋", "璀璨", "纹丝不动", "凝神", "屏息",
          "脱口而出", "字正腔圆", "气喘吁吁", "摇摇欲坠", "火星儿",
        ],
        category: "read_word",
        pinyin: [
          "zhèn ěr yù lóng", "cuǐ càn", "wén sī bù dòng", "níng shén", "bǐng xī",
          "tuō kǒu ér chū", "zì zhèng qiāng yuán", "qì chuǎn xū xū", "yáo yáo yù zhuì", "huǒ xīng er",
        ],
      },
      {
        label: "N/L Contrast Words I",
        type: "multisyllabic",
        words: ["亲人", "清人", "信任", "新任", "认真"],
        category: "read_word",
        pinyin: ["qīn rén", "qīng rén", "xìn rèn", "xīn rèn", "rèn zhēn"],
      },
      {
        label: "N/L Contrast Words II",
        type: "multisyllabic",
        words: ["任正", "人参", "人生", "深沉", "生成"],
        category: "read_word",
        pinyin: ["rèn zhèng", "rén shēn", "rén shēng", "shēn chén", "shēng chéng"],
      },
    ],
    mcqQuestions: [
      {
        context: "你穿过竹林，眼前出现一片无边无际的平原。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这地方贼安静", "这地方非常安静", "这地方老安静了"],
        correctIndex: 1,
      },
      {
        context: "微风轻轻拂过，草地泛起层层涟漪。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["草被风吹得直晃悠", "草被风吹得直摇晃", "草被风吹得直摆动"],
        correctIndex: 1,
      },
      {
        context: "天空突然裂开一道缝隙，金色的光芒从天而降。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这场景真震撼", "这场景忒震撼", "这场景超震撼"],
        correctIndex: 0,
      },
      {
        context: "守护者的声音深沉如钟，震得你的胸口发麻。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这声音挺有力量", "这声音怪有力量", "这声音蛮有力量"],
        correctIndex: 0,
      },
      {
        context: "守护者向你微微颔首，表示认可。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["他朝你点了点头", "他冲你点了点头", "他对你点了点头"],
        correctIndex: 2,
      },
      {
        context: "守护者的声音在山谷中回荡。",
        prompt: "下面哪个句子语法正确？",
        options: ["你听见了守护者的声音", "你听守护者的声音了", "你把守护者的声音听见了"],
        correctIndex: 0,
      },
      {
        context: "你握紧法杖，准备接受考验。",
        prompt: "下面哪个句子语法正确？",
        options: ["你把法杖握在手里", "你握法杖在手里", "你在手里握法杖"],
        correctIndex: 0,
      },
      {
        context: "你念错了一个字，守护者立刻做出反应。",
        prompt: "下面哪个句子语法正确？",
        options: ["一道闪电把你肩头劈", "一道闪电劈你肩头在", "一道闪电劈在你肩头"],
        correctIndex: 2,
      },
      {
        context: "你念对了一个复杂的词，守护者露出赞许的神色。",
        prompt: "下面哪个句子语法正确？",
        options: ["你让守护者点头了", "守护者对你点了点头", "守护者冲你点了头"],
        correctIndex: 1,
      },
      {
        context: "闪电劈下来的时候，你浑身一颤。",
        prompt: "下面哪个句子语法正确？",
        options: ["你被闪电劈中了肩膀", "你让闪电劈中了肩膀", "你给闪电劈中了肩膀"],
        correctIndex: 0,
      },
      {
        prompt: "天空中飘着一_____云彩。下面哪个量词使用正确？",
        options: ["片", "朵", "块"],
        correctIndex: 1,
      },
      {
        prompt: "守护者手中握着一_____发光的法杖。下面哪个量词使用正确？",
        options: ["根", "条", "把"],
        correctIndex: 0,
      },
      {
        prompt: "一道闪电劈下来，你的肩上留下了一_____焦痕。下面哪个量词使用正确？",
        options: ["道", "条", "片"],
        correctIndex: 0,
      },
      {
        prompt: "守护者说话时，嘴里吐出的每一_____字都像钟声一样响亮。下面哪个量词使用正确？",
        options: ["粒", "颗", "个"],
        correctIndex: 2,
      },
      {
        prompt: "试炼结束时，你长长地舒了一_____气。下面哪个量词使用正确？",
        options: ["口", "股", "阵"],
        correctIndex: 0,
      },
      {
        context: "他扛着行李上了火车。",
        prompt: "请选择加点字的正确读音。",
        options: ["káng", "gāng"],
        correctIndex: 0,
        highlightedChar: "扛",
      },
      {
        context: "他力能扛鼎，是出了名的大力士。",
        prompt: "请选择加点字的正确读音。",
        options: ["káng", "gāng"],
        correctIndex: 1,
        highlightedChar: "扛",
      },
      {
        context: "他卷起袖子开始干活。",
        prompt: "请选择加点字的正确读音。",
        options: ["juǎn", "juàn"],
        correctIndex: 0,
        highlightedChar: "卷",
      },
      {
        context: "他把试卷交上去就出来了。",
        prompt: "请选择加点字的正确读音。",
        options: ["juǎn", "juàn"],
        correctIndex: 1,
        highlightedChar: "卷",
      },
      {
        context: "他撒腿就跑，一下子就没了影。",
        prompt: "请选择加点字的正确读音。",
        options: ["sā", "sǎ"],
        correctIndex: 0,
        highlightedChar: "撒",
      },
      {
        context: "他撒了一地水，赶紧拿拖把擦。",
        prompt: "请选择加点字的正确读音。",
        options: ["sā", "sǎ"],
        correctIndex: 1,
        highlightedChar: "撒",
      },
      {
        context: "他解开了绳子，把箱子打开。",
        prompt: "请选择加点字的正确读音。",
        options: ["jiě", "jiè", "xiè"],
        correctIndex: 0,
        highlightedChar: "解",
      },
      {
        context: "他解送犯人去了法院。",
        prompt: "请选择加点字的正确读音。",
        options: ["jiě", "jiè", "xiè"],
        correctIndex: 1,
        highlightedChar: "解",
      },
      {
        context: "他姓解，这个姓很少见。",
        prompt: "请选择加点字的正确读音。",
        options: ["jiě", "jiè", "xiè"],
        correctIndex: 2,
        highlightedChar: "解",
      },
      {
        context: "他和颜悦色地跟我说话。",
        prompt: "请选择加点字的正确读音。",
        options: ["hé", "hè", "huó", "huò"],
        correctIndex: 0,
        highlightedChar: "和",
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["漂亮", "靓", "好看", "美"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["干净", "清洁", "清爽", "净办"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["舒服", "舒坦", "受用", "好过"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["着急", "心急", "发急", "急眼"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["开心", "快乐", "高兴", "欢喜"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["想念", "想", "思念", "惦记"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）耳朵",
        options: ["只", "个", "对", "扇", "片"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）墙",
        options: ["面", "道", "堵", "个", "扇"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）葡萄",
        options: ["颗", "粒", "个", "串", "枝"],
        correctIndex: 3,
      },
      {
        prompt: "一（ ）钢琴",
        options: ["架", "台", "个", "座", "具"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）被子",
        options: ["床", "条", "张", "个", "套"],
        correctIndex: 0,
      },
    ],
  },
  /* ─── Stage 7 ─── 6 recording groups (15 mono + 15 mono + 10 multi + 10 multi + 10 n/l + C4 passage) ─── */
  7: {
    recordingGroups: [
      {
        label: "Monosyllabic Characters I",
        type: "monosyllabic",
        words: [
          "享", "茬", "松", "蟹", "登",
          "块", "柑", "伐", "愁", "鞋",
          "锐", "关", "癞", "想", "若",
        ],
        category: "read_syllable",
        pinyin: [
          "xiǎng", "chá", "sōng", "xiè", "dēng",
          "kuài", "gān", "fá", "chóu", "xié",
          "ruì", "guān", "lài", "xiǎng", "ruò",
        ],
      },
      {
        label: "Monosyllabic Characters II",
        type: "monosyllabic",
        words: [
          "澈", "蔫", "床", "毡", "欺",
          "鸟", "投", "景", "随", "奉",
          "存", "懂", "笙", "诊", "箭",
        ],
        category: "read_syllable",
        pinyin: [
          "chè", "niān", "chuáng", "zhān", "qī",
          "niǎo", "tóu", "jǐng", "suí", "fèng",
          "cún", "dǒng", "shēng", "zhěn", "jiàn",
        ],
      },
      {
        label: "Multisyllabic Words I",
        type: "multisyllabic",
        words: [
          "皇宫", "铜镜", "矗立", "扭曲", "空洞",
          "腐化", "残影", "主宰", "囚徒", "秃鹫",
        ],
        category: "read_word",
        pinyin: [
          "huáng gōng", "tóng jìng", "chù lì", "niǔ qū", "kōng dòng",
          "fǔ huà", "cán yǐng", "zhǔ zǎi", "qiú tú", "tū jiù",
        ],
      },
      {
        label: "Multisyllabic Words II",
        type: "multisyllabic",
        words: [
          "深呼吸", "回荡", "嘶吼", "溃散", "前所未有",
          "透亮", "消散", "青烟", "清澈", "温和",
        ],
        category: "read_word",
        pinyin: [
          "shēn hū xī", "huí dàng", "sī hǒu", "kuì sàn", "qián suǒ wèi yǒu",
          "tòu liang", "xiāo sàn", "qīng yān", "qīng chè", "wēn hé",
        ],
      },
      {
        label: "N/L Contrast Words",
        type: "multisyllabic",
        words: [
          "泥巴", "农历", "奴隶", "努力", "绿篱",
          "女篮", "男篮", "来年", "老娘", "老农",
        ],
        category: "read_word",
        pinyin: [
          "ní bā", "nóng lì", "nú lì", "nǔ lì", "lǜ lí",
          "nǚ lán", "nán lán", "lái nián", "lǎo niáng", "lǎo nóng",
        ],
      },
      {
        label: "Passage Reading",
        type: "passage",
        words: [],
        passageText: "你推开宫门，愣在原地。\n没有宝座，没有妖魔。只有一面面铜镜矗立其间，每一面都映出你的身影——有的模糊，有的扭曲，有的嘴唇翕动却发不出声。死一般的寂静压得你喘不过气。\n\u201C你来了。\u201D\n声音从四面八方涌来。你握紧法杖，循声望去。大殿尽头，一面最高的铜镜前，站着一个身影——那是你，又不完全是你。周身笼罩灰暗的光，眼神空洞，嘴唇不停开合，却没有声音。\n铜镜炸裂。他走了出来。\n孙悟空扭曲的幻影。曾经的语言主宰，如今的语音囚徒。他靠吞食错误发音为生——你一路走来念错的每一个字，都成了滋养他的养料。\n没有退路。你举起法杖。\n他率先出手。刺耳的音波扑面而来，你耳膜剧痛，脚步踉跄。你开口念出第一个字——声调刚出口，你就知道错了。喘息未定，音走了样。破碎的音节呼啸着扑上来，撕咬你的肩膀。剧痛让你几乎失声。\n不能慌。你咬紧牙，站稳脚跟，再次开口。这一次声音稳了，字字饱满，掷地有声。那个词念完的瞬间，法杖顶端炸开一团金光——光芒直直劈向他的胸口。他嘶吼着后退半步。\n你冲了上去。你踩着自己的节奏，每一步配合一次发音。他挥爪抓来，你念出一个字，金光砸在他的额头；他张嘴咆哮，你再念一字，金光刺进他的喉咙；他周身阴影翻涌，第三字出口，金光撕开他胸口的黑暗。他踉跄着后退，身影越来越淡。\n最后一个字落下。法杖迸发出前所未有的光芒，照亮整个大殿。所有铜镜里的扭曲身影同时消散，只剩下你自己的倒影，清晰而坚定。\n他化作一缕青烟，消失在空气中。\n穹顶缓缓打开，金色的阳光倾泻而下。一个声音从天际传来，清澈如泉水：\n\u201C谢谢你。语言的力量，终于恢复了。\u201D\n你握紧法杖，望向天空。阳光照在脸上，温暖而明亮。",
        category: "read_chapter",
      },
    ],
    mcqQuestions: [
      {
        context: "你推开宫殿大门，眼前的情景让你震惊。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["这地方咋这么安静", "这地方怎么这么安静", "这地方咋地这么安静"],
        correctIndex: 1,
      },
      {
        context: "每一面镜子里都映出你的身影，但每一道身影都不一样。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["有的模糊不清", "有的迷糊不清", "有的模乎不清"],
        correctIndex: 0,
      },
      {
        context: "那身影周身笼罩着灰暗的光，眼神空洞。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["他的眼神吓人", "他的眼神瘆人", "他的眼神骇人"],
        correctIndex: 0,
      },
      {
        context: "你握紧法杖，准备迎接最后的战斗。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["我以为他能赢", "我意思他能赢", "我觉着他能赢"],
        correctIndex: 0,
      },
      {
        context: "你举起法杖，准备迎接最后的战斗。",
        prompt: "下面哪个说法是普通话正确说法？",
        options: ["别磨叽了，上吧", "别磨洋工了，上吧", "别磨蹭了，上吧"],
        correctIndex: 2,
      },
      {
        context: "那身影从镜中走了出来。",
        prompt: "下面哪个句子语法正确？",
        options: ["他从镜子里走出来了", "他走出来从镜子里了", "他走出来镜子从里"],
        correctIndex: 0,
      },
      {
        context: "他靠吞食错误的发音为生。",
        prompt: "下面哪个句子语法正确？",
        options: ["他把错误的发音吞食", "错误的发音被他吞食", "他吞食错误的发音"],
        correctIndex: 2,
      },
      {
        context: "你念错了字，他的力量就会增强。",
        prompt: "下面哪个句子语法正确？",
        options: ["你被错误增强了力量", "错误让你增强了力量", "错误被他增强了力量"],
        correctIndex: 1,
      },
      {
        context: "你念对了，法杖迸发的金光就能撕裂他周身的阴影。",
        prompt: "下面哪个句子语法正确？",
        options: ["金光把阴影撕裂了", "金光被阴影撕裂了", "阴影把金光撕裂了"],
        correctIndex: 0,
      },
      {
        context: "所有的磨练，都是为了这一刻。",
        prompt: "下面哪个句子语法正确？",
        options: ["这一刻被你等待", "你等待这一刻", "这一刻让你等待"],
        correctIndex: 1,
      },
      {
        context: "你深吸一口气，开口念出第一个字。",
        prompt: "下面哪个句子语法正确？",
        options: ["你把第一个字念得清清楚楚", "你念第一个字得清清楚楚", "你念第一个字清清楚楚得"],
        correctIndex: 0,
      },
      {
        context: "他的身影化作一缕青烟，消失在空气中。",
        prompt: "下面哪个句子语法正确？",
        options: ["青烟被空气中消失了", "青烟在空气中消失了", "青烟把空气中消失了"],
        correctIndex: 1,
      },
      {
        context: "法杖顶端炸开一团金光，照亮整个大殿。",
        prompt: "下面哪个句子语法正确？",
        options: ["整个大殿被照亮了", "整个大殿把照亮了", "整个大殿让照亮了"],
        correctIndex: 0,
      },
      {
        context: "大殿的穹顶缓缓打开，金色的阳光倾泻而下。",
        prompt: "下面哪个句子语法正确？",
        options: ["阳光照得你睁不开眼睛", "阳光照你睁不开眼睛", "阳光照得你眼睛睁不开"],
        correctIndex: 0,
      },
      {
        context: "天空中传来一个清澈如泉水的声音。",
        prompt: "下面哪个句子语法正确？",
        options: ["声音被你听见了", "你听见了声音", "你把声音听见了"],
        correctIndex: 1,
      },
      {
        context: "边塞的风光壮丽辽阔。",
        prompt: "请选择加点字的正确读音。",
        options: ["sāi", "sài"],
        correctIndex: 1,
        highlightedChar: "塞",
      },
      {
        context: "他饮了一口茶，慢慢说道。",
        prompt: "请选择加点字的正确读音。",
        options: ["yǐn", "yìn"],
        correctIndex: 0,
        highlightedChar: "饮",
      },
      {
        context: "他饮马河边，休息片刻。",
        prompt: "请选择加点字的正确读音。",
        options: ["yǐn", "yìn"],
        correctIndex: 1,
        highlightedChar: "饮",
      },
      {
        context: "这孩子很省心，从不惹麻烦。",
        prompt: "请选择加点字的正确读音。",
        options: ["shěng", "xǐng"],
        correctIndex: 0,
        highlightedChar: "省",
      },
      {
        context: "你要省悟过来，别再犯错了。",
        prompt: "请选择加点字的正确读音。",
        options: ["shěng", "xǐng"],
        correctIndex: 1,
        highlightedChar: "省",
      },
      {
        context: "他把衣服熨平整了。",
        prompt: "请选择加点字的正确读音。",
        options: ["yù", "yùn"],
        correctIndex: 1,
        highlightedChar: "熨",
      },
      {
        context: "他心里熨帖多了，不再烦躁。",
        prompt: "请选择加点字的正确读音。",
        options: ["yù", "yùn"],
        correctIndex: 0,
        highlightedChar: "熨",
      },
      {
        context: "他把字帖在墙上。",
        prompt: "请选择加点字的正确读音。",
        options: ["tiē", "tiě", "tiè"],
        correctIndex: 0,
        highlightedChar: "帖",
      },
      {
        context: "他买了一本帖子练字。",
        prompt: "请选择加点字的正确读音。",
        options: ["tiē", "tiě", "tiè"],
        correctIndex: 2,
        highlightedChar: "帖",
      },
      {
        context: "他扒开草丛寻找钥匙。",
        prompt: "请选择加点字的正确读音。",
        options: ["bā", "pá"],
        correctIndex: 0,
        highlightedChar: "扒",
      },
      {
        prompt: "一（ ）尾巴",
        options: ["条", "根", "个", "段", "只"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）刷子",
        options: ["把", "个", "根", "支", "柄"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）香烟",
        options: ["根", "支", "条", "包", "盒"],
        correctIndex: 1,
      },
      {
        prompt: "一（ ）黄瓜",
        options: ["根", "条", "个", "段", "棵"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）项链",
        options: ["条", "根", "串", "个", "副"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）皮带",
        options: ["条", "根", "段", "个", "副"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）竹子",
        options: ["根", "条", "棵", "节", "竿"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）桥",
        options: ["座", "条", "道", "个", "孔"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）诗",
        options: ["首", "篇", "段", "句", "则"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）牛",
        options: ["头", "只", "条", "匹", "个"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）镜子",
        options: ["面", "块", "张", "个", "架"],
        correctIndex: 0,
      },
      {
        prompt: "一（ ）飞机",
        options: ["架", "艘", "只", "台", "个"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["这汤淡太了", "这汤太淡了", "这汤淡得很"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["你起床了没", "你起床没", "你起了床没有"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["他写很慢", "他写得很慢", "他写字很慢"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["我送他一本书", "我送一本书他", "我把一本书送他"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["你下班几点", "你几点下班", "你几点钟下班"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["他吃很快", "他吃得很快", "他吃快得很"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["我认得她", "我认识她", "我她认识"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["你喝水了吗", "你喝水了没有", "你喝没喝水"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["这风景美真", "这风景真美", "这风景美得很"],
        correctIndex: 1,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["他住在哪儿", "他住哪儿", "他在哪儿住"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个句子语法正确？",
        options: ["我买了五本书", "我买五本书了", "我五本书买了"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["西红柿", "番茄", "洋柿子", "红茄"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["客厅", "堂屋", "厅下", "厅堂"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["学校", "学堂", "书院", "学舍"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["老师", "先生", "教书匠", "教授"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["同学", "同窗", "学友", "窗友"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["朋友", "友仔", "盆友", "友朋"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["漂亮", "靓", "好看", "美"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["干净", "清洁", "清爽", "净办"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["舒服", "舒坦", "受用", "好过"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["着急", "心急", "发急", "急眼"],
        correctIndex: 0,
      },
      {
        prompt: "下面哪个是普通话标准说法？",
        options: ["开心", "快乐", "高兴", "欢喜"],
        correctIndex: 0,
      },
      {
        context: "他们在哄堂大笑。",
        prompt: "请选择加点字的正确读音。",
        options: ["hǒng", "hòng", "hōng"],
        correctIndex: 2,
        highlightedChar: "哄",
      },
      {
        context: "这场哄乱很快平息了。",
        prompt: "请选择加点字的正确读音。",
        options: ["hǒng", "hòng", "hōng"],
        correctIndex: 1,
        highlightedChar: "哄",
      },
      {
        context: "他把书夹在胳膊下。",
        prompt: "请选择加点字的正确读音。",
        options: ["jiā", "jiá"],
        correctIndex: 0,
        highlightedChar: "夹",
      },
      {
        context: "这件夹克很合身。",
        prompt: "请选择加点字的正确读音。",
        options: ["jiā", "jiá"],
        correctIndex: 0,
        highlightedChar: "夹",
      },
      {
        context: "他挣扎着站了起来。",
        prompt: "请选择加点字的正确读音。",
        options: ["zhēng", "zhèng"],
        correctIndex: 0,
        highlightedChar: "挣",
      },
      {
        context: "他挣了不少钱。",
        prompt: "请选择加点字的正确读音。",
        options: ["zhēng", "zhèng"],
        correctIndex: 1,
        highlightedChar: "挣",
      },
      {
        context: "他把绳子系在树上。",
        prompt: "请选择加点字的正确读音。",
        options: ["xì", "jì"],
        correctIndex: 1,
        highlightedChar: "系",
      },
      {
        context: "他们关系很好。",
        prompt: "请选择加点字的正确读音。",
        options: ["xì", "jì"],
        correctIndex: 0,
        highlightedChar: "系",
      },
      {
        context: "他朝东边走去。",
        prompt: "请选择加点字的正确读音。",
        options: ["cháo", "zhāo"],
        correctIndex: 0,
        highlightedChar: "朝",
      },
      {
        context: "他朝气蓬勃，充满活力。",
        prompt: "请选择加点字的正确读音。",
        options: ["cháo", "zhāo"],
        correctIndex: 1,
        highlightedChar: "朝",
      },
    ],
  },
};
